import {catalog,analyze} from './engine.js?v=3';
export const SHAPES=['Kingpost','Simple Fink','Queen','Fink','Howe','Fan','Modified Queen','Double Fink','Double Howe','Common','Gable','Dual Ridge','Scissor','Hip Scissor','Mono Scissor','Mono','Dropped Mono Gable','Dual Ridge Mono','Cathedral','Hip Cathedral','Mono Cathedral','Symmetrical Cathedral','Non-Symmetrical Cathedral','Cambered','Cambered Hip','Cathedral Tray','Dual Pitch','California Hip','California Hip Cathedral','California Hip Tray','California Mono Hip','California Hip Scissor','California Hip Studio Vault','California Hip Cambered','Tall Bearing Cathedral','Tall Bearing','Polynesian','Polynesian Hip','Porch','Stepdown Hip','Mono Stepdown Hip','Stepdown Hip 2','Studio Vault','Attic','Attic Hip','Gambrel','Gambrel Attic','Flat','Sloping Flat','Parallel Chord Scissor','Parallel Chord Mono','Parapet','Sloping Parapet',"Mac's Parapet",'Tray','Hip Tray','Common Coffer','Hip Coffer','Scissor with Offset Bearing','Cathedral with Offset Bearing','Cape','Common with Offset Bearing','Hip with Offset Bearing','Bow','Barrel','Bow Barrel','Common Cap','Hip Cap','Mono Cap','Mono Hip Cap','Inverted'];
export const WEB_STYLES=['Fink','Howe','Pratt','Fan','Warren','Queen','Kingpost'];
export function shapeWeb(s){return WEB_STYLES.find(w=>s.toLowerCase().includes(w.toLowerCase()))||'Fink';}
const distance=(a,b)=>Math.hypot(...a.map((x,i)=>x-b[i])),lerp=(a,b,t)=>a.map((x,i)=>x+(b[i]-x)*t);
export function templateMembers(t,{panel=1.2,style='Fink',shape='Fink',overhang=0}={}){
 const top=[];for(let i=1;i<t.profile.length;i++){const a=t.profile[i-1],b=t.profile[i],n=style==='Kingpost'?1:Math.max(1,Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])/panel));if(i===1)top.push(a);for(let j=1;j<=n;j++)top.push(lerp(a,b,j/n));}
 const bot=top.map(p=>[p[0],p[1],t.base]),ms=[],seen=new Set(),add=(a,b,role)=>{const L=distance(a,b);if(L<.005)return;const k=[a.map(x=>x.toFixed(5)).join(','),b.map(x=>x.toFixed(5)).join(',')].sort().join('/');if(seen.has(k))return;seen.add(k);ms.push({a:[...a],b:[...b],role,length:L,section:[.0381,.0889],sectionName:'2x4',material:'timber',thickness:.0381});};
 const n=top.length-1,mid=Math.floor(n/2);for(let i=0;i<n;i++){add(top[i],top[i+1],'top');add(bot[i],bot[i+1],'bottom');let down=style==='Howe'?i>=n/2:style==='Pratt'?i<n/2:style==='Fink'?Math.floor(i/2)%2===0:i%2===0;add(down?top[i]:bot[i],down?bot[i+1]:top[i+1],'web');}for(let i=0;i<=n;i++)add(bot[i],top[i],'web');if(style==='Fan')for(let i=1;i<n;i++)add(bot[mid],top[i],'web');if(style==='Queen'&&n>=3)add(top[Math.floor(n/3)],top[Math.ceil(2*n/3)],'web');
 if(overhang>0){const ends=t.full?[0,n]:[top[0][2]<top[n][2]?0:n];for(const i of ends){const inner=top[i===0?1:n-1],p=top[i],vx=p[0]-inner[0],vy=p[1]-inner[1],run=Math.hypot(vx,vy);if(run>.001){/* Overhang is entered as perpendicular eave projection. A diagonal hip carrier therefore needs a longer along-member tail (sqrt(2) at 45deg), unlike ordinary trusses/jacks. */const planFactor=t.type==='Hip carrier'?1/Math.max(Math.abs(vx/run),Math.abs(vy/run),.35):1,tail=overhang*planFactor;add(p,p.map((x,k)=>x+(x-inner[k])*tail/run),'overhang');}}}
 return ms;
}
export const woodCatalog=[3.5,5.5,7.25,9.25,11.25].map((d,i)=>{const b=38.1,h=d*25.4,A=b*h;return {name:['2x4','2x6','2x8','2x10','2x12'][i],A,I:h*b**3/12,kgm:A*.0005,E:1600000*.006894757,b,d:h};});
function makeAnalytical(t,extras=[]){const nodes=[],ids=new Map(),origin=t.profile[0],end=t.profile.at(-1),L=Math.hypot(end[0]-origin[0],end[1]-origin[1]),u=[(end[0]-origin[0])/L,(end[1]-origin[1])/L],ix=p=>{const xy=[((p[0]-origin[0])*u[0]+(p[1]-origin[1])*u[1])*1000,(p[2]-t.base)*1000],key=xy.map(x=>x.toFixed(3)).join(',');if(!ids.has(key)){ids.set(key,nodes.length);nodes.push(xy);}return ids.get(key);};
 const sourceIndices=[],members=t.members.flatMap((m,i)=>{if(m.role==='overhang')return [];sourceIndices.push(i);return [{a:ix(m.a),b:ix(m.b),role:m.role,L:m.length*1000}]});const tops=[...new Set(members.filter(m=>m.role==='top').flatMap(m=>[m.a,m.b]))].sort((a,b)=>nodes[a][0]-nodes[b][0]),bottom=[...new Set(members.filter(m=>m.role==='bottom').flatMap(m=>[m.a,m.b]))].sort((a,b)=>nodes[a][0]-nodes[b][0]);if(!tops.length||bottom.length<2)throw Error('Missing chord or bearing nodes');const supports=[bottom[0],...extras.map(x=>bottom[x]),bottom.at(-1)],fixed=[2*bottom[0],...supports.map(n=>n*2+1)];return {nodes,members,top:tops,bottom,xs:tops.map(i=>nodes[i][0]/1000),supports,fixed,sourceIndices};}
function loadCases(p){
 const tw=p.trib*.3048, psf=.047880258, D=(p.dead||0)*psf*tw, Lr=(p.roofLive||0)*psf*tw, S=(p.snow||0)*psf*tw, W=(p.wind||0)*psf*tw, B=(p.bottomLive||0)*psf*tw;
 const strength=[
  ['D',D],['D + Lr',D+Lr],['D + S',D+S],['D + 0.75Lr + 0.75S',D+.75*Lr+.75*S],
  ['D + W down',D+W],['0.6D + W uplift',.6*D-W],['D + 0.75Lr + 0.75W',D+.75*Lr+.75*W],
  ['D + bottom chord live',D+B],['Unbalanced roof live',D+.75*Lr],['Unbalanced snow',D+.75*S],
  ['Construction / point allowance',D+Math.max(Lr,(p.construction||0)*psf*tw)],['User special',D+(p.special||0)*psf*tw]
 ];
 return {strength,service:[['Service D+Lr',D+Lr],['Service D+S',D+S],['Service wind',D-W],['Service bottom',D+B]]};
}
function size(t,p,extra){const g=makeAnalytical(t,extra),library=woodCatalog,E=library[0].E,allow=p.allow*.006894757,indices={top:0,bottom:0,web:0};let last;
 for(let iter=0;iter<library.length*3;iter++){
  const sections=Object.fromEntries(Object.keys(indices).map(k=>{const s=library[indices[k]];return [k,{...s,A:s.A*t.ply,I:s.I*t.ply,kgm:s.kgm*t.ply}]}));
  const lc=loadCases(p),cases=[];for(const [name,q] of [...lc.strength,...lc.service]){const r=analyze(g,sections,q,1);cases.push({name,q,...r});}
  const members=g.members.map((m,i)=>{const s=sections[m.role],yieldCap=s.A*allow,euler=Math.PI**2*E*s.I/m.L**2;let ratio=0,force=0,governing='';for(const c of cases.slice(0,lc.strength.length)){const f=c.forces[i],capacity=f<0?Math.min(yieldCap,euler):yieldCap,r=Math.abs(f)/Math.max(capacity,1e-9);if(r>=ratio){ratio=r;force=f;governing=c.name;}}return {index:g.sourceIndices[i],role:m.role,length:m.L/1000,force:force/1000,ratio,size:library[indices[m.role]].name,ply:t.ply,governing,compression:force<0,axialCapacity:(force<0?Math.min(yieldCap,euler):yieldCap)/1000};});
  const service=cases.slice(lc.strength.length),deflection=Math.max(...service.map(c=>c.deflection)),deflectionCase=service.sort((a,b)=>b.deflection-a.deflection)[0]?.name||'—',ratio=Math.max(...members.map(m=>m.ratio)),mass=g.members.reduce((sum,m)=>sum+m.L/1000*sections[m.role].kgm,0),pass=ratio<=1&&deflection<=t.span*1000/p.limit;
  const gov=members.sort((a,b)=>b.ratio-a.ratio)[0];
  last={pass,ratio,displacement:deflection,deflectionCase,members,reactions:cases.map(c=>({case:c.name,reactions:c.reactions.map(x=>({x:x.x,force:x.vertical/1000}))})),extra:extra.map(i=>g.nodes[g.bottom[i]][0]/1000),sections:Object.fromEntries(Object.keys(indices).map(k=>[k,library[indices[k]]])),mass,status:pass?'PRELIMINARY PASS':'DESIGN REQUIRED',basis:'2D pin-jointed timber truss screening with multiple gravity/uplift/service load cases; connection plates, code-specific factors and full member interaction require engineering verification',governingMember:gov?.index,governingCase:gov?.governing,loadCases:cases.map(c=>({name:c.name,lineLoad_kNm:c.q,totalVertical_kN:c.totalVertical/1000}))};
  if(pass)return last;const needs=new Set(members.filter(m=>m.ratio>1).map(m=>m.role));if(deflection>t.span*1000/p.limit)Object.keys(indices).forEach(k=>needs.add(k));let changed=false;for(const k of needs)if(indices[k]<library.length-1){indices[k]++;changed=true;}if(!changed)break;
 }return last;
}
export function analyzeAssemblyTruss(t,p,{styles=WEB_STYLES,panel=1.2,shape='Fink',overhang=0,edited=false}={}){
 for(const [key,min,max] of [['dead',0,500],['roofLive',0,500],['snow',0,500],['wind',0,500],['bottomLive',0,500],['construction',0,500],['special',-500,500],['trib',.1,20],['allow',1,10000],['fy',100,600],['limit',100,1000]])if(!Number.isFinite(p[key])||p[key]<min||p[key]>max)throw Error(`Invalid ${key}`);
 p={...p,material:'timber'};let bestFail=null,trials=0;
 for(let count=0;count<=(p.supports==='ends'?0:2);count++){for(let ply=1;ply<=3;ply++){let best=null;for(const style of styles){const candidate={...t,ply,members:edited?t.members:templateMembers(t,{panel,style,shape,overhang})},g=makeAnalytical(candidate),internals=g.bottom.map((_,i)=>i).slice(1,-1),sets=count===0?[[]]:count===1?internals.map(i=>[i]):internals.flatMap((i,k)=>internals.slice(k+1).map(j=>[i,j]));for(const extra of sets){try{const a=size(candidate,p,extra);trials++;a.style=style;a.trials=trials;a.ply=ply;const trial={...candidate,analysis:a};if(a.pass&&(!best||a.mass<best.analysis.mass))best=trial;if(!bestFail||a.ratio<bestFail.analysis.ratio)bestFail=trial;}catch(e){bestFail ||= {...candidate,analysis:{pass:false,status:'UNSTABLE / REVIEW',error:e.message,members:[],extra:[],ratio:null,displacement:null,style,mass:Infinity,ply}};}}}if(best){best.analysis.trials=trials;return best;}}}
 return bestFail||{...t,analysis:{pass:false,status:'NO CANDIDATE',members:[],extra:[]}};
}
export function dxfSegments(text,scale=1){const lines=text.replace(/\r/g,'').split('\n'),pairs=[];for(let i=0;i+1<lines.length;i+=2)pairs.push([Number(lines[i].trim()),lines[i+1].trim()]);let type='',data=[],segments=[],poly=[],closed=false,entities=false;
 const flush=()=>{const val=k=>Number(data.find(p=>p[0]===k)?.[1]||0);if(type==='LINE')segments.push([[val(10),val(20),val(30)],[val(11),val(21),val(31)]]);if(type==='LWPOLYLINE'){let pts=[];for(let i=0;i<data.length;i++)if(data[i][0]===10){let y=0;for(let j=i+1;j<data.length&&data[j][0]!==10;j++)if(data[j][0]===20)y=Number(data[j][1]);pts.push([Number(data[i][1]),y,0]);}for(let i=1;i<pts.length;i++)segments.push([pts[i-1],pts[i]]);if(val(70)&1&&pts.length)segments.push([pts.at(-1),pts[0]]);}if(type==='POLYLINE'){poly=[];closed=!!(val(70)&1);}if(type==='VERTEX')poly.push([val(10),val(20),val(30)]);if(type==='SEQEND'){for(let i=1;i<poly.length;i++)segments.push([poly[i-1],poly[i]]);if(closed&&poly.length)segments.push([poly.at(-1),poly[0]]);poly=[];}};
 for(const [code,value] of pairs){if(code===0){if(entities)flush();type=value;data=[];if(value==='ENDSEC')entities=false;}else if(code===2&&value==='ENTITIES')entities=true;else if(entities)data.push([code,value]);}if(entities)flush();if(!segments.length)throw Error('No LINE, LWPOLYLINE or POLYLINE entities found.');if(segments.some(s=>s.flat().some(x=>!Number.isFinite(x))))throw Error('Invalid DXF coordinate.');return segments.map(s=>s.map(p=>p.map(x=>x*scale)));}
export function exportDXF(assembly){let s='0\nSECTION\n2\nHEADER\n9\n$INSUNITS\n70\n6\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n';for(const t of assembly.trusses)for(const m of t.members)s+=`0\nLINE\n8\n${t.id}_${m.role}\n10\n${m.a[0]}\n20\n${m.a[1]}\n30\n${m.a[2]}\n11\n${m.b[0]}\n21\n${m.b[1]}\n31\n${m.b[2]}\n`;return s+'0\nENDSEC\n0\nEOF\n';}
export function parametricRoof({width,length,plate,pitch,spacing,style}){if([width,length,spacing].some(x=>!Number.isFinite(x)||x<=0)||!Number.isFinite(plate)||!Number.isFinite(pitch)||pitch<=0||width>100||length>100||spacing<.2)throw Error('Enter valid dimensions (up to 100 m) and spacing at least 0.2 m.');const axes=[],add=(a,b)=>{if(distance(a,b)>.02)axes.push({a,b,name:`R${axes.length+1}`})},height=(x,y)=>plate+pitch*(style==='HIP'?Math.min(width/2-Math.abs(x),length/2-Math.abs(y)):width/2-Math.abs(x));const n=Math.max(2,Math.ceil(length/spacing));for(let i=1;i<n;i++){let y=-length/2+i*length/n,half=style==='HIP'?Math.min(width/2,length/2-Math.abs(y)):width/2;add([-width/2,y,plate],[-width/2+half,y,height(-width/2+half,y)]);add([width/2-half,y,height(width/2-half,y)],[width/2,y,plate]);if(half<width/2-.01)add([-width/2+half,y,plate+pitch*half],[width/2-half,y,plate+pitch*half]);}if(style==='HIP'){const m=Math.ceil(width/spacing);for(let i=1;i<m;i++){const x=-width/2+i*width/m,run=Math.min(width/2-Math.abs(x),length/2);add([x,-length/2,plate],[x,-length/2+run,plate+pitch*run]);add([x,length/2-run,plate+pitch*run],[x,length/2,plate]);}}return {axes,meshes:[],origin:[0,0,0],bounds:[width,length,Math.min(width,length)/2*pitch],parametric:true};}
