import {geometry,optimize,validate} from './engine.js';
import {parseOBJ,parseIFC,pairRafters} from './importer.js';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(x,n=2)=>Number(x).toFixed(n);
let view='truss',result=null,imported=null,results=new Map(),busy=false,yaw=-.55,selected=-1,revision=0;
const roles={top:'Top chord',bottom:'Bottom chord',web:'Web'},colors={top:'#c9f36a',bottom:'#66b5eb',web:'#a8bac5'};
function message(s,error=false){$('message').textContent=s;$('message').style.color=error?'#af4c32':'#647d46';}
function params(pair){const p=Object.fromEntries(['span','rise','spacing','fy','dead','live','wind','fd','fl','fw','fs','limit'].map(k=>[k,Number($(k).value)]));p.apex=p.span/2;p.layout=$('layout').value;p.bearings=$('bearings').value;p.eligible=$('eligible').value.trim()?$('eligible').value.split(',').map(s=>s.trim()?Number(s):NaN):[];if(pair)Object.assign(p,{span:pair.span,rise:pair.rise,apex:pair.apex});validate(p);return p;}
function pair(){return imported?.pairs[Number($('pair').value)||0];}
function baseGeometry(){try{const p=params(pair());return geometry(p.span,p.rise,p.apex,8,'Pratt');}catch{return geometry(12,2.8,6,8,'Pratt');}}
function invalidate(){if(busy)return;revision++;result=null;results.clear();selected=-1;$('result-state').textContent='Inputs changed · regenerate';render();}
function memberColor(m){if(!result)return colors[m.role];if($('color').value==='util')return m.ratio>1?'#ef836e':m.ratio>.8?'#f4c76c':'#b2dd77';if($('color').value==='force')return m.force<0?'#ef9b74':'#76bceb';return colors[m.role];}
function draw(){const g=result||baseGeometry();let html='';const line=(a,b,attrs='')=>`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" ${attrs}/>`;
 if(view==='truss'){
 const scale=Math.min(820/(g.span*1000),250/(g.rise*1000)),ox=(1000-g.span*1000*scale)/2,oy=370,pt=([x,y])=>[ox+x*scale,oy-y*scale];
 html+=line([60,oy+20],[940,oy+20],'stroke="#31434f" stroke-dasharray="4 7"');
 g.members.forEach((m,i)=>{html+=line(pt(g.nodes[m.a]),pt(g.nodes[m.b]),`class="member ${i===selected?'selected':''}" data-member="${i}" tabindex="0" role="button" aria-label="Inspect ${m.id}" stroke="${memberColor(m)}" stroke-width="${m.role==='web'?2.3:4}" stroke-linecap="round"`)});
 g.nodes.forEach(p=>{const [x,y]=pt(p);html+=`<circle cx="${x}" cy="${y}" r="3" fill="#17242d" stroke="#a1b0b9" stroke-width="1.2"/>`});
 g.supports.forEach((node,i)=>{const [x,y]=pt(g.nodes[node]);html+=`<path d="M${x},${y+7}l-9,15h18z" fill="#f4ba6622" stroke="#f4ba66" stroke-width="1.6"/><text x="${x}" y="${y+43}" fill="#c99d65" text-anchor="middle" font-family="monospace" font-size="11">B${i+1}${i>0&&i<g.supports.length-1?'*':''}</text>`});
 const left=pt([0,0])[0],right=pt([g.span*1000,0])[0];html+=line([left,435],[right,435],'stroke="#4b606e"');[left,right].forEach(x=>html+=line([x,428],[x,442],'stroke="#4b606e"'));html+=`<rect x="440" y="423" width="120" height="24" fill="#17242d"/><text x="500" y="440" text-anchor="middle" fill="#8ca2af" font-family="monospace" font-size="12">${fmt(g.span)} m</text>`;
 const loads=Number($('dead').value)+Number($('live').value);if(Number.isFinite(loads)&&loads>0)for(let i=1;i<g.top.length-1;i++){const [x,y]=pt(g.nodes[g.top[i]]);html+=`<path d="M${x} ${y-34}v23m-4-5l4 5 4-5" fill="none" stroke="#8098a866" stroke-width="1.3"/>`;}
 }else{
 const segments=[];
 if(imported){for(const r of imported.axes)segments.push({a:r.a,b:r.b,color:'#51636f',w:2});for(let k=0;k<imported.pairs.length;k++){const p=imported.pairs[k],r=results.get(k)||(k===Number($('pair').value)?g:null);if(!r)continue;const dx=(p.right[0]-p.left[0])/p.span,dy=(p.right[1]-p.left[1])/p.span,world=([x,z])=>[p.left[0]+x/1000*dx,p.left[1]+x/1000*dy,p.left[2]+z/1000];r.members.forEach(m=>segments.push({a:world(r.nodes[m.a]),b:world(r.nodes[m.b]),color:k===Number($('pair').value)?colors[m.role]:'#637680',w:k===Number($('pair').value)?2.6:1.5}));}}
 else for(let k=0;k<6;k++)g.members.forEach(m=>segments.push({a:[g.nodes[m.a][0]/1000,k*Number($('spacing').value),g.nodes[m.a][1]/1000],b:[g.nodes[m.b][0]/1000,k*Number($('spacing').value),g.nodes[m.b][1]/1000],color:k===0?colors[m.role]:'#627983',w:k===0?3:1.5}));
 if(segments.length){const proj=p=>[p[0]*Math.cos(yaw)-p[1]*Math.sin(yaw),(p[0]*Math.sin(yaw)+p[1]*Math.cos(yaw))*.36-p[2]],ss=segments.map(s=>({...s,a:proj(s.a),b:proj(s.b)})),ps=ss.flatMap(s=>[s.a,s.b]),xs=ps.map(p=>p[0]),ys=ps.map(p=>p[1]),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys),sc=Math.min(800/Math.max(.1,maxx-minx),290/Math.max(.1,maxy-miny)),pt=p=>[500+(p[0]-(minx+maxx)/2)*sc,270+(p[1]-(miny+maxy)/2)*sc];ss.forEach(s=>html+=line(pt(s.a),pt(s.b),`stroke="${s.color}" stroke-width="${s.w}" stroke-linecap="round"`));}
 }
 $('model').innerHTML=html;$('model-caption').textContent=view==='roof'?(result?'Rafter axes + generated trusses · drag to rotate':'Rafter axes + preview layout · drag to rotate'):result?`${g.pattern} · ${g.n} panels · ${g.members.length} members · metres`:'Geometry preview · generate to analyze';$('view-hint').textContent=view==='roof'?'Drag to rotate roof':'Select a member to inspect';
 document.querySelector('.legend').innerHTML=$('color').value==='role'||!result||view==='roof'?'<span><i class="top"></i>Top chord</span><span><i class="bottom"></i>Bottom chord</span><span><i class="web"></i>Webs</span><span><i class="bearing"></i>Bearings</span>':$('color').value==='util'?'<span><i style="background:#b2dd77"></i>≤ 0.80</span><span><i style="background:#f4c76c"></i>0.80–1.00</span><span><i style="background:#ef836e"></i>> 1.00</span>':'<span><i style="background:#ef9b74"></i>Compression</span><span><i style="background:#76bceb"></i>Tension</span>';
}
function render(){draw();if(!result){$('bearing-note').textContent='Generate to search bearing locations';$('defl-note').textContent='Vertical displacement envelope';$('result-state').textContent='Not analyzed · generate study';for(const k of ['bearings','mass','util','defl'])$('m-'+k).textContent='—';$('members').innerHTML='<div class="empty">Generate a study to compare web layouts and member sizes.</div>';$('supports').innerHTML='<div class="empty">Bearing reactions will appear after analysis.</div>';return;}
 const r=result;$('m-bearings').innerHTML=String(r.supports.length)+` <em>/ truss</em>`;$('m-mass').innerHTML=fmt(r.mass,1)+' <em>kg</em>';$('m-util').textContent=fmt(r.maxRatio);$('m-defl').innerHTML=fmt(r.deflection,1)+' <em>mm</em>';$('defl-note').textContent=`Limit ${fmt(r.span*1000/r.params.limit,1)} mm · span/${r.params.limit}`;$('bearing-note').textContent=r.supports.length>2?`${r.supports.length-2} new locations need review`:'No internal bearing required by screening';$('result-state').textContent=r.pass?`Screened · ${r.trials} alternatives`:'No feasible screening result';
 $('members').innerHTML='<table><thead><tr><th>Member</th><th>Stud section · mm</th><th>Length</th><th>Axial envelope</th><th>Ratio</th></tr></thead><tbody>'+r.members.map((m,i)=>`<tr data-member="${i}" tabindex="0" role="button" aria-label="Inspect ${m.id}"><td><strong>${m.id}</strong> <span class="muted">${roles[m.role]}</span></td><td>${m.section.name}</td><td>${fmt(m.L/1000)} m</td><td>${fmt(Math.abs(m.force)/1000,1)} kN <span class="muted">${m.force<0?'C':'T'}</span></td><td><span class="ratio"><span class="bar"><i style="width:${Math.min(100,m.ratio*100)}%;background:${m.ratio>1?'#d67e64':'#a3c46d'}"></i></span>${fmt(m.ratio)}</span></td></tr>`).join('')+'</tbody></table>';
 $('supports').innerHTML='<table><thead><tr><th>Bearing</th><th>Position from left</th><th>Max downward</th><th>Max uplift</th><th>Status</th></tr></thead><tbody>'+r.supports.map((node,i)=>{const reactions=r.cases.slice(0,2).map(c=>c.reactions[i].vertical);return `<tr><td>B${i+1}</td><td>${fmt(r.nodes[node][0]/1000)} m</td><td>${fmt(Math.max(0,...reactions)/1000)} kN</td><td>${fmt(Math.max(0,...reactions.map(x=>-x))/1000)} kN</td><td><span class="pill warn">${i===0||i===r.supports.length-1?'Assumed end bearing':'Proposed · needs approval'}</span></td></tr>`}).join('')+'</tbody></table><p class="muted" style="padding:0 20px">Reactions are factored envelopes. Uplift needs a verified tie-down. Proposed points do not establish walls, columns or foundation capacity.</p>';
}
async function generate(){if(busy)return;if(imported&&!$('confirm').checked){message('Confirm the imported axes and scale before generating.',true);return;}let list;try{list=imported?imported.pairs.map(p=>params(p)):[params()];if(!list.length)throw Error('No rafter pairs are available.');}catch(e){message(e.message,true);return;}busy=true;$('generate').disabled=true;document.querySelectorAll('aside input,aside select,#demo').forEach(e=>e.disabled=true);const rev=revision;try{results.clear();result=null;render();for(let i=0;i<list.length;i++){message(`Analyzing truss ${i+1} of ${list.length}…`);const r=await optimize(list[i],({count,trials})=>message(`Truss ${i+1}/${list.length} · ${trials} alternatives · ${count+2} bearings`));if(revision!==rev)throw Error('Geometry changed. Generate again.');results.set(i,r);}result=results.get(imported?Number($('pair').value):0);render();const failed=[...results.values()].filter(r=>!r.pass).length;message(failed?`${failed} truss(es) have no feasible result in this search. See analysis notes.`:`${results.size} truss study/studies generated. Preliminary screening only.`,failed>0);}catch(e){message(e.message,true);}finally{busy=false;$('generate').disabled=false;document.querySelectorAll('aside input,aside select,#demo').forEach(e=>e.disabled=false);$('span').disabled=$('rise').disabled=!!imported;}}
function inspect(i){if(!result){message('Generate a study to inspect forces and selected sections.');return;}const m=result.members[i];if(!m)return;selected=i;draw();$('detail-body').innerHTML=`<div class="eyebrow">${roles[m.role]}</div><h2>${m.id} · ${m.section.name}</h2><p>Length <strong>${fmt(m.L/1000,3)} m</strong><br>Governing axial force <strong>${fmt(m.force/1000)} kN</strong> (${m.force<0?'compression':'tension'})<br>Governing case <strong>${m.governing}</strong><br>Screening ratio <strong>${fmt(m.ratio,3)}</strong></p><p>Gross area ${fmt(m.section.A)} mm²<br>Weak-axis second moment ${fmt(m.section.I,0)} mm⁴<br>Gross yield force ${fmt(m.yieldCap/1000)} kN<br>Ideal Euler force ${fmt(m.euler/1000)} kN</p><p class="muted">Generic thin-wall section properties. No manufacturer certification, effective-width or local/distortional buckling checks. Axial screening is not a code-compliance check.</p>`;$('detail').showModal();}
async function loadFile(file){if(!file||busy)return;if(!/\.(ifc|obj)$/i.test(file.name)){message('Choose an IFC or OBJ file.',true);return;}if(file.size>25*1024*1024){message('File is larger than 25 MB. Export a simplified rafter-only model.',true);return;}busy=true;$('generate').disabled=true;message('Reading rafter geometry…');try{const parsed=/\.obj$/i.test(file.name)?parseOBJ(await file.text(),Number($('units').value),$('axis').value==='Y up'):await parseIFC(await file.arrayBuffer());if(!parsed.axes.length)throw Error('No straight rafter axes detected. Export separate, straight rafter solids or OBJ lines.');const paired=pairRafters(parsed.axes);if(!paired.pairs.length)throw Error(`Found ${parsed.axes.length} axes but no compatible pitched rafter pairs. This version requires two straight slopes meeting at a ridge, with level eaves. Check OBJ units/up axis.`);if(paired.pairs.length>50)throw Error('More than 50 trusses detected. Split the roof into smaller studies.');imported={...parsed,...paired,name:file.name};revision++;results.clear();result=null;$('pair').innerHTML=imported.pairs.map((p,i)=>`<option value="${i}">${p.id} · ${fmt(p.span)} m span</option>`).join('');$('import-review').hidden=false;$('confirm').checked=false;$('source-info').textContent=`${file.name} · ${parsed.axes.length} axes`;$('import-detail').textContent=`${paired.pairs.length} paired trusses; ${paired.unpaired} unpaired axes; ${parsed.skipped} non-slender objects skipped. Axes are approximate. Verify spacing and loads; these are not inferred from the file.`;selectPair();view='roof';setView(view);message('Import ready. Inspect the axes, confirm scale, then generate.');}catch(e){message(`Import failed: ${e.message}`,true);}finally{busy=false;$('generate').disabled=false;$('file').value='';}}
function selectPair(){const p=pair();if(!p)return;$('span').value=fmt(p.span,3);$('rise').value=fmt(p.rise,3);$('span').disabled=$('rise').disabled=true;$('model-title').textContent=`${p.id} / ${imported.name}`;result=results.get(Number($('pair').value))||null;selected=-1;render();}
function setView(v){view=v;document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===v);b.setAttribute('aria-selected',b.dataset.view===v)});draw();}
function showPanel(p){document.querySelectorAll('[data-panel]').forEach(b=>{b.classList.toggle('active',b.dataset.panel===p);b.setAttribute('aria-selected',b.dataset.panel===p)});['members','supports','analysis'].forEach(id=>$(id).hidden=id!==p);}
const urls=[];
function downloadButton(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));urls.push(url);return `<a class="secondary" style="display:block;margin:12px 0;text-decoration:none" href="${url}" download="${name}">${esc(name)}</a>`;}
function exports(){if(!results.size){message('Generate a study before exporting.',true);return;}urls.forEach(URL.revokeObjectURL);urls.length=0;const data={status:'PRELIMINARY — NOT FOR CONSTRUCTION',source:imported?.name||'Parametric example',created:new Date().toISOString(),scope:'2D pin-jointed axial screening; no code-compliance, connection, bracing or foundation verification',axes:imported?.axes||null,studies:[...results].map(([i,r])=>({truss:`T${i+1}`,result:r}))},csv=['Status,Truss,Member,Role,Section_mm,Length_m,Force_kN,Screening_ratio'];let obj='# PRELIMINARY STUDY — NOT FOR CONSTRUCTION\n# Units: metres; Z up; line geometry only\n',offset=1;for(const [i,r] of results){r.members.forEach(m=>csv.push(`PRELIMINARY,T${i+1},${m.id},${m.role},${m.section.name},${fmt(m.L/1000,4)},${fmt(m.force/1000,4)},${fmt(m.ratio,4)}`));obj+=`o Truss_${i+1}\n`;const p=imported?.pairs[i];r.nodes.forEach(([x,z])=>{const v=p?[p.left[0]+x/1000*(p.right[0]-p.left[0])/p.span,p.left[1]+x/1000*(p.right[1]-p.left[1])/p.span,p.left[2]+z/1000]:[x/1000,0,z/1000];obj+=`v ${v.join(' ')}\n`;});r.members.forEach(m=>obj+=`l ${m.a+offset} ${m.b+offset}\n`);offset+=r.nodes.length;}$('detail-body').innerHTML='<div class="eyebrow">STUDY EXPORT</div><h2>Take the study with you.</h2><p>All analyzed trusses, member sizes and assumptions. These files are preliminary and are not fabrication drawings.</p>'+downloadButton('rafter-study.json',JSON.stringify(data,null,2),'application/json')+downloadButton('member-schedule.csv',csv.join('\r\n'),'text/csv')+downloadButton('truss-axes.obj',obj,'text/plain');$('detail').showModal();}
$('generate').addEventListener('click',generate);$('file').addEventListener('change',e=>loadFile(e.target.files[0]));$('drop').addEventListener('dragover',e=>{e.preventDefault();$('drop').classList.add('drag')});$('drop').addEventListener('dragleave',()=>$('drop').classList.remove('drag'));$('drop').addEventListener('drop',e=>{e.preventDefault();$('drop').classList.remove('drag');loadFile(e.dataTransfer.files[0])});$('pair').addEventListener('change',selectPair);$('color').addEventListener('change',draw);$('bearings').addEventListener('change',()=>{$('eligible-wrap').hidden=$('bearings').value!=='allowed'});
document.querySelectorAll('aside input:not([type=file]):not([type=checkbox]),aside select:not(#pair)').forEach(e=>e.addEventListener('change',invalidate));$('confirm').addEventListener('change',()=>{if(!$('confirm').checked)invalidate()});document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>showPanel(b.dataset.panel)));
for(const id of ['model','members']){$(id).addEventListener('click',e=>{const el=e.target.closest('[data-member]');if(el)inspect(Number(el.dataset.member));});$(id).addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){const el=e.target.closest('[data-member]');if(el){e.preventDefault();inspect(Number(el.dataset.member))}}});}
$('close-detail').onclick=()=>$('detail').close();$('detail').addEventListener('click',e=>{if(e.target===$('detail'))$('detail').close()});$('export').onclick=exports;$('fit').onclick=()=>{yaw=-.55;selected=-1;draw()};let dragX=null;$('model').addEventListener('pointerdown',e=>{if(view==='roof'){dragX=e.clientX;$('model').setPointerCapture(e.pointerId)}});$('model').addEventListener('pointermove',e=>{if(dragX!==null){yaw+=(e.clientX-dragX)*.008;dragX=e.clientX;draw()}});$('model').addEventListener('pointerup',()=>dragX=null);$('model').addEventListener('pointercancel',()=>dragX=null);
$('demo').onclick=()=>{if(busy)return;imported=null;revision++;$('span').disabled=$('rise').disabled=false;$('span').value=12;$('rise').value=2.8;$('import-review').hidden=true;$('source-info').textContent='Example geometry · 6 rafter pairs';$('model-title').textContent='T01 / Example roof';setView('truss');generate()};
render();generate();
if(document.modelContext?.registerTool){const abort=new AbortController();window.addEventListener('pagehide',()=>abort.abort(),{once:true});const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:abort.signal})).catch(()=>{});}catch{}};register({name:'read_truss_study',description:'Read the current preliminary truss study. Does not certify structural safety.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({source:imported?.name||'example',analyzed:results.size,selected:result?{span:result.span,pattern:result.pattern,bearings:result.supports.length,mass:result.mass,screeningRatio:result.maxRatio,screeningPass:result.pass}:null,status:'Preliminary; not code verified'})});register({name:'configure_example_loads',description:'Change example-roof loads in kPa and invalidate previous analysis; does not run analysis or edit an imported model.',inputSchema:{type:'object',properties:{dead:{type:'number',minimum:0,maximum:20},live:{type:'number',minimum:0,maximum:20},wind:{type:'number',minimum:0,maximum:20}},required:['dead','live','wind'],additionalProperties:false},execute:input=>{if(busy||imported)throw Error('Load configuration is available only for an idle example model.');if(!input||Object.keys(input).some(k=>!['dead','live','wind'].includes(k)))throw Error('Invalid input.');for(const k of ['dead','live','wind'])if(typeof input[k]!=='number'||!Number.isFinite(input[k])||input[k]<0||input[k]>20)throw Error('Load must be between 0 and 20 kPa.');for(const k of ['dead','live','wind'])$(k).value=input[k];invalidate();return {configured:true,analysis:'not run'};}});}
