import {setupAdvanced} from './advanced-ui.js?v=4';
import {parseRoofOBJ,assembleRoof,fromIFCAxes,typeColors} from './roof.js?v=3';
import {parseIFC} from './importer.js?v=3';
import {inspectDXF,parseRoofDXF} from './dxf-importer.js?v=3';
import {RoofViewer} from './viewer.js?v=5';
import {solidMemberEnds} from './connection-geometry.js?v=3';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(n,d=2)=>Number(n).toFixed(d);
let advanced=null;
let source=null,assembly=null,selected=null,name='NW 6th St',filter='All',mode='iso',raw=null,rawKind='obj',dxfInfo=null,busy=false,drawZoom=1,drawPan=[0,0],lastURLs=[];
let viewer;try{viewer=new RoofViewer($('three'),select);}catch(e){$('three').innerHTML='<p style="padding:100px 30px">3D graphics unavailable. Enable WebGL or open in a supported desktop browser.</p>';message('WebGL could not start: '+e.message,true);}
function message(s,error=false){$('message').textContent=s;$('message').style.color=error?'#eead8c':'#afc598';}
function current(){return assembly?.trusses.find(t=>t.id===selected);}
function settings(){const heel=Number($('heel').value)/1000,panel=Number($('panel').value)/1000;if(!Number.isFinite(heel)||heel<.05||heel>1.2)throw Error('Heel depth must be 50–1,200 mm.');if(!Number.isFinite(panel)||panel<.3||panel>2.4)throw Error('Panel length must be 300–2,400 mm.');return {heel,panel,inferHips:$('hips').checked};}
function generate(){if(!source||busy)return;try{const opts=settings(),next=assembleRoof(source,opts);if(!next.trusses.length)throw Error('No compatible framing planes could be assembled.');assembly=next;advanced?.configureAssembly(assembly);selected=assembly.trusses.some(t=>t.id===selected)?selected:assembly.trusses[0].id;filter='All';if(viewer){viewer.filter='All';viewer.isolate=false;viewer.setModel(source,assembly);viewer.select(selected);}$('isolate').setAttribute('aria-pressed','false');$('cut').value=100;viewer?.section(100);update();message(`${assembly.covered}/${assembly.sourceAxisCount} rafter axes used · ${assembly.trusses.length} trusses · ${assembly.inferred} inferred hip carriers. Geometry only; engineering review required.`);}catch(e){message(e.message,true);}}
async function importData(data,filename,kind){if(busy)return;busy=true;$('generate').disabled=true;message('Reading the full model…');try{let next;if(kind==='obj')next=parseRoofOBJ(data,Number($('units').value),$('axis').value);else if(kind==='ifc')next=fromIFCAxes((await parseIFC(data)).axes);else {dxfInfo=inspectDXF(data);const layers=dxfInfo.layers;const setOptions=(id,prefer)=>{$(id).innerHTML=layers.map(x=>`<option ${x.toUpperCase()===prefer?'selected':''}>${esc(x)}</option>`).join('');};setOptions('roof-layer','ROOF');const trussesLayer=layers.find(x=>x.trim().toUpperCase()==='TRUSSES');$('truss-layer').innerHTML=trussesLayer?`<option selected>${esc(trussesLayer)}</option>`:'<option selected>TRUSSES (required)</option>';$('truss-layer').disabled=true;$('cad-options').hidden=false;next=parseRoofDXF(data,{roofLayer:$('roof-layer').value,trussLayer:'TRUSSES',pitchDeg:Number($('roof-angle').value),unit:$('cad-units').value});}
 if(kind!=='dxf'){$('cad-options').hidden=true;dxfInfo=null;}if(next.axes.length>5000)throw Error('This model has more than 5,000 generated rafter/top-chord axes. Split it into roof zones.');if(Math.max(...next.bounds)>300||Math.max(...next.bounds)<.2)throw Error('The model scale is outside 0.2–300 m. Check the selected units and import again.');source=next;raw=data;rawKind=kind;name=filename.replace(/\.(obj|ifc|dxf)$/i,'');selected=null;$('project-name').textContent=name;$('dimensions').textContent=`${fmt(source.bounds[0])} × ${fmt(source.bounds[1])} m · ${source.axes.length} top-chord segments${kind==='dxf'?` · ROOF ref ${source.cad?.roofEntityCount||0} · TRUSSES ${source.cad?.trussEntityCount||0}`:''}`;busy=false;generate();}catch(e){message('Import failed: '+e.message,true);}finally{busy=false;$('generate').disabled=false;}}
async function loadFile(f){if(!f||busy)return;if(!/\.(obj|ifc|dxf)$/i.test(f.name)){message('Select an OBJ, IFC or DXF file.',true);return;}if(f.size>25*1024*1024){message('File exceeds 25 MB.',true);return;}const lower=f.name.toLowerCase(),kind=lower.endsWith('.ifc')?'ifc':lower.endsWith('.dxf')?'dxf':'obj';await importData(kind==='ifc'?await f.arrayBuffer():await f.text(),f.name,kind);$('file').value='';}
async function preset(){try{$('units').value='.0254';if(!$('units').value)$('units').value='0.0254';$('axis').value='Z';const response=await fetch('./nw-6th-st.obj');if(!response.ok)throw Error('Project file unavailable.');await importData(await response.text(),'NW 6th St.obj','obj');}catch(e){message(e.message,true);}}
function update(){if(!assembly)return;$('coverage').textContent=`${assembly.covered} / ${assembly.sourceAxisCount} RAFTERS INCLUDED`;$('count').textContent=assembly.trusses.length;$('families').innerHTML=`<button data-family="All" class="${filter==='All'?'active':''}">All <strong>${assembly.trusses.length}</strong></button>`+Object.entries(assembly.counts).map(([type,count])=>`<button data-family="${type}" class="${filter===type?'active':''}"><i style="background:${typeColors[type]}"></i>${type}<strong>${count}</strong></button>`).join('');schedule();selection();draw();}
function schedule(){if(!assembly)return;const q=$('search').value.toLowerCase();$('schedule').innerHTML=assembly.trusses.filter(t=>(filter==='All'||t.type===filter)&&`${t.id} ${t.type}`.toLowerCase().includes(q)).map(t=>`<button class="truss-row ${t.id===selected?'active':''}" data-truss="${t.id}" aria-pressed="${t.id===selected}"><i style="background:${typeColors[t.type]}"></i><strong>${t.id}</strong><span>${t.type}${t.proposed?' *':''}</span><small>${fmt(t.span)}m</small></button>`).join('')||'<p class="help">No matching trusses.</p>';}
function select(id,index){if(!assembly?.trusses.some(t=>t.id===id))return;selected=id;advanced?.selectionChanged(id,index);viewer?.select(id);drawZoom=1;drawPan=[0,0];schedule();selection();draw();if(viewer?.isolate)viewer.fit();}
function selection(){const t=current();if(!t)return;const transferred=t.connections.map(c=>c.to).join(', ');$('selection').innerHTML=`<h2>${t.id}<span>${t.type}${t.proposed?' · inferred':''}</span></h2><div class="selection-metrics"><div><strong>${fmt(t.span)} m</strong>Span</div><div><strong>${fmt(t.height)} m</strong>Height</div><div><strong>${t.members.length*t.ply}</strong>Members</div></div><div class="edit-row"><label>Classification<select id="edit-type">${Object.keys(typeColors).filter(k=>!['Unclassified','Mono'].includes(k)).map(k=>`<option ${k===t.type?'selected':''}>${k}</option>`).join('')}</select></label><label>Plies<select id="edit-ply">${[1,2,3,4].map(n=>`<option ${n===t.ply?'selected':''}>${n}</option>`).join('')}</select></label></div><p>${t.sources.length} source rafter(s) · ${transferred?'Candidate transfer to '+esc(transferred):t.full?'End bearings assumed':'No receiving truss identified'}. ${esc(t.review)}.</p>`;$('edit-type').onchange=()=>{t.type=$('edit-type').value;t.review='Manual classification — structural role unverified';assembly.counts={};assembly.trusses.forEach(t=>assembly.counts[t.type]=(assembly.counts[t.type]||0)+1);rebuildView();update();};$('edit-ply').onchange=()=>{t.ply=Number($('edit-ply').value);advanced?.invalidate();rebuildView();selection();message('Ply count changed for visualization. Capacity and connections are not verified.');};}
function rebuildView(){if(viewer){viewer.setModel(source,assembly);viewer.select(selected);viewer.section(Number($('cut').value));}}
function setView(v){mode=v;document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===v);b.setAttribute('aria-selected',b.dataset.view===v)});$('viewports').classList.toggle('split',v==='split');$('drawing-pane').hidden=v!=='split';viewer?.setView(v==='split'?'iso':v);if(viewer){viewer.layers.labels=(v==='plan');viewer.updateVisibility();}$('view-title').textContent={iso:'FULL ROOF / PERSPECTIVE',plan:'ROOF PLAN / ORTHOGRAPHIC',front:'FRONT / ORTHOGRAPHIC',side:'SIDE / ORTHOGRAPHIC',split:'3D + SELECTED TRUSS ELEVATION'}[v];document.querySelector('.nav-hint').textContent=['iso','split'].includes(v)?'Drag to orbit · right-drag to pan · scroll to zoom':'Drag to pan · scroll to zoom · select a truss';draw();}
function drawingSVG(t){const origin=t.profile[0],d=[t.profile.at(-1)[0]-origin[0],t.profile.at(-1)[1]-origin[1]],L=Math.hypot(...d),u=d.map(x=>x/L),s=Math.min(650/L,270/t.height),pt=p=>[75+((p[0]-origin[0])*u[0]+(p[1]-origin[1])*u[1])*s,340-(p[2]-t.base)*s],line=(a,b,c,w=2)=>`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${c}" stroke-width="${w}"/>`;let str='<defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#e5ebef" stroke-width=".5"/></pattern></defs><rect width="800" height="460" fill="url(#grid)"/>';
 str+=`<g transform="translate(${drawPan[0]} ${drawPan[1]}) translate(400 230) scale(${drawZoom}) translate(-400 -230)">`;for(const m of t.members)str+=line(pt(m.a),pt(m.b),m.role==='top'?'#376944':m.role==='bottom'?'#377ba7':'#8197a4',m.role==='web'?1.7:3.5);const a=pt([origin[0],origin[1],t.base]),b=pt([t.profile.at(-1)[0],t.profile.at(-1)[1],t.base]);str+=line([a[0],390],[b[0],390],'#899ca8',1);for(const x of [a[0],b[0]])str+=line([x,355],[x,400],'#bac6ce',1);str+=`<rect x="${(a[0]+b[0])/2-57}" y="378" width="114" height="24" fill="#f5f7f8"/><text x="${(a[0]+b[0])/2}" y="394" text-anchor="middle" fill="#526d7d" font-size="14" font-family="monospace">${fmt(t.span)} m</text>`;for(const p of [a,b,...(t.analysis?.extra||[]).map(x=>[a[0]+x*s,a[1]])])str+=`<path d="M${p[0]} ${p[1]+4}l-8 15h16z" fill="none" stroke="#b3864e" stroke-width="1.5"/>`;str+=`<text x="75" y="425" fill="#879aa6" font-size="12">${t.id} · ${t.type} · ${t.ply} ply · CadTech wood-truss geometry</text></g>`;return str;}
function draw(){const t=current();if(!t)return;$('drawing-title').textContent=`${t.id} / ${t.type.toUpperCase()} / ELEVATION`;$('drawing').innerHTML=drawingSVG(t);}
function save(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));lastURLs.push(url);return `<a href="${url}" download="${name}">${esc(name)}</a>`;}
function exportModel(){if(!assembly)return;lastURLs.forEach(URL.revokeObjectURL);lastURLs=[];let obj='# CadTech wood roof truss assembly\n# Units: metres. Z up. Local origin documented in JSON.\n',vi=1;const faces=[[0,1,2,3],[4,7,6,5],[0,4,5,1],[1,5,6,2],[2,6,7,3],[3,7,4,0]];
 // Export closed rectangular member envelopes; visualization uses lipped-C shapes.
 for(const t of assembly.trusses){obj+=`o ${t.id}_${t.type.replace(/ /g,'_')}\n`;for(let ply=0;ply<t.ply;ply++)for(const m of t.members){const o=(ply-(t.ply-1)/2)*.055,trim=solidMemberEnds(t,m,assembly,o);if(trim.hidden)continue;const ma=trim.a,mb=trim.b,ml=Math.max(1e-9,Math.hypot(...mb.map((x,i)=>x-ma[i]))),dir=mb.map((x,i)=>(x-ma[i])/ml),n=[...t.normal,0],z=[dir[1]*n[2]-dir[2]*n[1],dir[2]*n[0]-dir[0]*n[2],dir[0]*n[1]-dir[1]*n[0]];for(const p of [ma,mb])for(const [w,h] of [[-1,-1],[1,-1],[1,1],[-1,1]])obj+='v '+p.map((x,i)=>x+n[i]*(o+w*m.section[0]/2)+z[i]*h*m.section[1]/2).join(' ')+'\n';faces.forEach(f=>obj+=`f ${f.map(k=>vi+k).join(' ')}\n`);vi+=8;}}
 const csv=['Truss,Type,Span_m,Height_m,Plies,Members,Source_rafters,Inferred,Status',...assembly.trusses.map(t=>`${t.id},${t.type},${fmt(t.span,4)},${fmt(t.height,4)},${t.ply},${t.members.length*t.ply},${t.sources.length},${t.proposed},CADTECH WOOD TRUSS`)].join('\r\n'),json={name,units:'metres',sourceOrigin:source.origin,inputUnits:rawKind==='obj'?Number($('units').value):'IFC model units',status:'CADTECH DESIGN DOCUMENT - FINAL ISSUE REQUIRES ENGINEERING REVIEW OF CONNECTIONS/BRACING/CODE INPUTS',settings:settings(),assembly};
 let links=save('roof-assembly.obj',obj,'text/plain')+save('truss-schedule.csv',csv,'text/csv')+save('roof-study.json',JSON.stringify(json,null,2),'application/json');const t=current();if(t){const priorZoom=drawZoom,priorPan=drawPan;drawZoom=1;drawPan=[0,0];links+=save(`${t.id}-elevation.svg`,`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="690" viewBox="0 0 800 460">${drawingSVG(t)}</svg>`,'image/svg+xml');drawZoom=priorZoom;drawPan=priorPan;}if(viewer)links+=`<a href="${viewer.exportPNG()}" download="roof-viewport.png">roof-viewport.png</a>`;$('downloads').innerHTML=links+'<p>OBJ contains solid member envelopes. The viewport shows solid dimensional-lumber sections with joint overlap for continuous wood framing. JSON preserves the original coordinate offset.</p>';$('export-dialog').showModal();}
$('generate').onclick=generate;$('preset').onclick=preset;$('file').onchange=e=>loadFile(e.target.files[0]);$('drop').ondragover=e=>{e.preventDefault();$('drop').classList.add('drag')};$('drop').ondragleave=()=>$('drop').classList.remove('drag');$('drop').ondrop=e=>{e.preventDefault();$('drop').classList.remove('drag');loadFile(e.dataTransfer.files[0])};$('search').oninput=schedule;$('schedule').onclick=e=>{const b=e.target.closest('[data-truss]');if(b)select(b.dataset.truss)};$('families').onclick=e=>{const b=e.target.closest('[data-family]');if(!b)return;filter=b.dataset.family;if(viewer){viewer.filter=filter;viewer.updateVisibility();}update();};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-orient]').forEach(b=>b.onclick=()=>setView(b.dataset.orient));document.querySelectorAll('[data-layer]').forEach(e=>e.onchange=()=>{if(viewer){viewer.layers[e.dataset.layer]=e.checked;viewer.updateVisibility();}});$('color').onchange=()=>{if(viewer){viewer.colorMode=$('color').value;viewer.updateVisibility();}};$('cut').oninput=()=>viewer?.section(Number($('cut').value));$('fit').onclick=()=>viewer?.fit();$('full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('viewports').requestFullscreen();}catch{message('Fullscreen is unavailable in this browser.');}};$('isolate').onclick=()=>{if(!viewer||!selected)return;viewer.isolate=!viewer.isolate;$('isolate').setAttribute('aria-pressed',viewer.isolate);viewer.updateVisibility();viewer.fit();};$('export').onclick=exportModel;$('close-export').onclick=()=>$('export-dialog').close();$('drawing-fit').onclick=()=>{drawZoom=1;drawPan=[0,0];draw();};let drag=null;$('drawing').onwheel=e=>{e.preventDefault();drawZoom=Math.max(.35,Math.min(5,drawZoom*Math.exp(-e.deltaY*.001)));draw();};$('drawing').onpointerdown=e=>{drag=[e.clientX,e.clientY];$('drawing').setPointerCapture(e.pointerId)};$('drawing').onpointermove=e=>{if(!drag)return;const s=800/$('drawing').clientWidth;drawPan[0]+=(e.clientX-drag[0])*s;drawPan[1]+=(e.clientY-drag[1])*s;drag=[e.clientX,e.clientY];draw();};$('drawing').onpointerup=() =>drag=null;$('drawing').onpointercancel=()=>drag=null;
for(const id of ['units','axis'])$(id).onchange=()=>{if(rawKind==='obj'&&raw)importData(raw,name+'.obj','obj');};
$('rebuild-cad').onclick=()=>{if(rawKind==='dxf'&&raw)importData(raw,name+'.dxf','dxf');};
for(const id of ['roof-layer','roof-angle','cad-units'])$(id).onchange=()=>{if(rawKind==='dxf')message('CAD roof settings changed. Click Rebuild CAD roof to apply them.');};
for(const id of ['heel','panel','hips'])$(id).onchange=()=>message('Generation settings changed. Generate complete roof to apply them.');
advanced=setupAdvanced({get:()=>({source,assembly,name,selected}),settings,notify:message,refresh:()=>{rebuildView();update();},png:()=>viewer?.exportPNG(),replaceSource:(s,n)=>{source=s;name=n;raw=null;selected=null;$('project-name').textContent=n;$('dimensions').textContent=`${fmt(s.bounds[0])} × ${fmt(s.bounds[1])} m`;generate();},restore:d=>{source=d.source;assembly=d.assembly;name=d.name||'Restored project';selected=d.selected||assembly.trusses[0]?.id;raw=null;$('project-name').textContent=name;$('dimensions').textContent=`${fmt(source.bounds[0])} × ${fmt(source.bounds[1])} m`;rebuildView();update();}});
window.addEventListener('pagehide',()=>viewer?.dispose(),{once:true});
if(document.modelContext?.registerTool){const reg=t=>{try{Promise.resolve(document.modelContext.registerTool(t)).catch(()=>{});}catch{}};reg({name:'read_roof_assembly',description:'Read framing counts, coverage and selected truss. Geometry only, not structural certification.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({project:name,counts:assembly?.counts,covered:assembly?.covered,sourceRafters:assembly?.sourceAxisCount,selected:current()?{id:current().id,type:current().type,span:current().span,proposed:current().proposed}:null,status:'Geometry generated; structural design unverified'})});reg({name:'select_roof_truss',description:'Select a truss in the visible roof model and its dimensioned elevation.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},execute:input=>{if(!input||typeof input.id!=='string'||!assembly?.trusses.some(t=>t.id===input.id))throw Error('Unknown truss ID');select(input.id);setView('split');return {selected:input.id,view:'split'};}});}
preset();
