// CadTech whole-building import intelligence. Geometry recognition only; engineering remains in whole-building solvers.
const FT=.3048;
const N=v=>Number(v)||0;
const layerClass=name=>{const s=String(name||'').toUpperCase();if(/DOOR|DR[-_ ]/.test(s))return'door';if(/WINDOW|WND|WIN[-_ ]/.test(s))return'window';if(/STAIR|VOID|OPENING|SHAFT/.test(s))return'floorOpening';if(/BEAM|LVL|GIRDER/.test(s))return'beam';if(/POST|COLUMN|COL[-_ ]/.test(s))return'post';if(/FLOOR|SLAB|DECK|EDGE/.test(s))return'floor';if(/WALL|A-WALL|PARTITION/.test(s))return'wall';if(/ROOF|TRUSS|RAFTER|RIDGE|HIP|VALLEY/.test(s))return'roof';return'other';};
function dxfUnits(text,override){if(override&&override!=='auto')return Number(override);const m=text.match(/\$INSUNITS\s*\r?\n\s*70\s*\r?\n\s*(\d+)/);return({1:.0254,2:.3048,4:.001,5:.01,6:1}[m?.[1]]||.0254);}
function pairs(text){const a=text.split(/\r?\n/),out=[];for(let i=0;i+1<a.length;i+=2)out.push([a[i].trim(),a[i+1].trim()]);return out;}
export function parseBuildingDXF(text,unitOverride='auto'){
 const u=dxfUnits(text,unitOverride),p=pairs(text),ents=[];let cur=null;
 const flush=()=>{if(cur)ents.push(cur);cur=null;};
 for(const [c,v] of p){if(c==='0'&&['LINE','LWPOLYLINE','POLYLINE'].includes(v)){flush();cur={type:v,layer:'0',pts:[],x:null};continue;}if(c==='0'&&cur){flush();continue;}if(!cur)continue;if(c==='8')cur.layer=v;if(c==='10'){cur.x=N(v)*u;}if(c==='20'&&cur.x!==null){cur.pts.push([cur.x,N(v)*u]);cur.x=null;}if(c==='11')cur.x2=N(v)*u;if(c==='21'&&cur.x2!==undefined){cur.pts.push([cur.x2,N(v)*u]);delete cur.x2;}}
 flush();const items=ents.filter(e=>e.pts.length>=2).map(e=>({...e,kind:layerClass(e.layer)}));const all=items.flatMap(e=>e.pts);if(!all.length)throw Error('No usable LINE/LWPOLYLINE building geometry found in DXF.');
 const xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),bbox={minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)};bbox.width=bbox.maxX-bbox.minX;bbox.length=bbox.maxY-bbox.minY;
 const walls=items.filter(e=>e.kind==='wall').flatMap((e,ei)=>e.pts.slice(1).map((b,i)=>({id:`DW${ei+1}-${i+1}`,a:e.pts[i],b,layer:e.layer}))).filter(s=>Math.hypot(s.b[0]-s.a[0],s.b[1]-s.a[1])>.2);
 const openings=items.filter(e=>e.kind==='door'||e.kind==='window').map((e,i)=>{const q=e.pts,c=[q.reduce((s,p)=>s+p[0],0)/q.length,q.reduce((s,p)=>s+p[1],0)/q.length],span=Math.max(...q.map(a=>Math.hypot(a[0]-c[0],a[1]-c[1])))*2;return{id:`O${i+1}`,type:e.kind==='door'?'Door':'Window',x:c[0],y:c[1],widthFt:Math.max(2,span/FT),heightFt:e.kind==='door'?6.67:4,sillFt:e.kind==='door'?0:3,layer:e.layer};});
 const floorOpenings=items.filter(e=>e.kind==='floorOpening').map((e,i)=>{const xx=e.pts.map(p=>p[0]),yy=e.pts.map(p=>p[1]);return{id:`FO${i+1}`,type:'Opening',xFt:(Math.min(...xx)-bbox.minX)/FT,yFt:(Math.min(...yy)-bbox.minY)/FT,widthFt:(Math.max(...xx)-Math.min(...xx))/FT,lengthFt:(Math.max(...yy)-Math.min(...yy))/FT};});
 return {format:'DXF',unitsM:u,bbox,walls,openings,floorOpenings,beams:items.filter(e=>e.kind==='beam'),posts:items.filter(e=>e.kind==='post'),floors:items.filter(e=>e.kind==='floor'),roof:items.filter(e=>e.kind==='roof'),layers:[...new Set(items.map(e=>e.layer))],recognition:'layer-aware'};
}
export function parseBuildingOBJ(text,scale=.0254,yUp=false){const verts=[];for(const line of text.split(/\r?\n/)){const s=line.trim().split(/\s+/);if(s[0]==='v'){const p=s.slice(1,4).map(Number);if(p.every(Number.isFinite)){const q=yUp?[p[0],-p[2],p[1]]:p;verts.push(q.map(x=>x*scale));}}}if(verts.length<4)throw Error('OBJ has insufficient geometry.');const xs=verts.map(p=>p[0]),ys=verts.map(p=>p[1]),zs=verts.map(p=>p[2]),bbox={minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys),minZ:Math.min(...zs),maxZ:Math.max(...zs)};bbox.width=bbox.maxX-bbox.minX;bbox.length=bbox.maxY-bbox.minY;return{format:'OBJ',bbox,walls:[],openings:[],floorOpenings:[],beams:[],posts:[],floors:[],roof:[],layers:[],recognition:'envelope-only',note:'OBJ has no reliable semantic wall/door/floor identities. CadTech uses its envelope and requires review/correction.'};}
export function mapImportedOpenings(imported,levels=1){if(!imported?.bbox)return[];const b=imported.bbox,tol=Math.max(.35,Math.min(b.width,b.length)*.05);return(imported.openings||[]).map(o=>{const d={W:Math.abs(o.x-b.minX),E:Math.abs(o.x-b.maxX),S:Math.abs(o.y-b.minY),N:Math.abs(o.y-b.maxY)},side=Object.entries(d).sort((a,b)=>a[1]-b[1])[0];return{...o,level:1,side:side[0],offsetFt:(side[0]==='N'||side[0]==='S'?(o.x-b.minX):(o.y-b.minY))/FT,status:side[1]<=tol?'AUTO-MAPPED':'REVIEW'};});}
export function importSummary(g){return{format:g.format,recognition:g.recognition,widthFt:g.bbox?.width/FT,lengthFt:g.bbox?.length/FT,walls:g.walls?.length||0,openings:g.openings?.length||0,floorOpenings:g.floorOpenings?.length||0,beams:g.beams?.length||0,posts:g.posts?.length||0,roofEntities:g.roof?.length||0,layers:g.layers||[],note:g.note||''};}
