// CadTech linked structural-object layer. Coordinates geometry/regeneration; does not certify capacities.
const N=v=>Number(v)||0, R=v=>Math.round(N(v)*1000)/1000;
export function buildObjectIndex(model,roof){const objects=[];for(const w of model?.walls||[])objects.push({id:w.id,type:'Wall',level:w.level,ref:w,props:{stud:w.studSize,spacingFt:w.studSpacingFt,heightFt:w.heightFt,bearing:w.bearing!==false}});for(const f of model?.floors||[]){objects.push({id:`FLOOR-L${f.level}`,type:'Floor',level:f.level,ref:f,props:{system:f.system,section:f.section,spacingFt:f.spacingFt}});for(const m of f.members||[])objects.push({id:m.id,type:'Floor member',level:f.level,ref:m,props:{kind:m.kind,section:m.section,spanFt:m.spanFt}});}for(const b of model?.beams||[])objects.push({id:b.id,type:'Beam',level:b.level||1,ref:b,props:{section:b.section,plies:b.plies,spanFt:b.spanFt}});for(const p of model?.posts||[])objects.push({id:p.id,type:'Post',level:p.level||1,ref:p,props:{section:p.section}});for(const t of roof?.trusses||[])objects.push({id:t.id,type:'Roof truss',level:(model?.levels||1)+1,ref:t,props:{family:t.type,ply:t.ply,status:t.design?.result||(t.analysis?.pass?'PASS':t.analysis?'FAIL':'NOT ANALYZED')}});model.objectIndex=objects;return objects;}
export function selectObjects(model,roof,mode,value){const a=buildObjectIndex(model,roof);if(mode==='failing')return a.filter(o=>['DESIGN REQUIRED','FAIL'].includes(o.props.status));if(mode==='review')return a.filter(o=>o.props.status==='REVIEW'||o.ref?.status==='REVIEW');if(mode==='type')return a.filter(o=>o.type===value);if(mode==='similar'){const src=a.find(o=>o.id===value);if(!src)return[];return a.filter(o=>o.type===src.type&&similarProps(o.props,src.props));}return a;}
function similarProps(a,b){const keys=['stud','system','section','kind','family','ply'];return keys.every(k=>a[k]==null||b[k]==null||a[k]===b[k]);}
export function objectProperties(model,roof,id){return buildObjectIndex(model,roof).find(o=>o.id===id)||null;}
export function updateObject(model,roof,id,patch={}){const o=objectProperties(model,roof,id);if(!o)return{ok:false,message:'Object not found'};const before=JSON.stringify(o.props);if(o.type==='Wall'){if(patch.section)o.ref.studSize=patch.section;if(N(patch.spacingFt)>0)o.ref.studSpacingFt=N(patch.spacingFt);if(N(patch.heightFt)>0)o.ref.heightFt=N(patch.heightFt);if(patch.bearing!=null)o.ref.bearing=!!patch.bearing;}else if(o.type==='Floor'){if(patch.system)o.ref.system=patch.system;if(patch.section)o.ref.section=patch.section;if(N(patch.spacingFt)>0)o.ref.spacingFt=N(patch.spacingFt);}else if(o.type==='Beam'){if(patch.section)o.ref.section=patch.section;if(N(patch.plies)>0)o.ref.plies=N(patch.plies);}else if(o.type==='Post'){if(patch.section)o.ref.section=patch.section;}else if(o.type==='Roof truss'){if(N(patch.ply)>0)o.ref.ply=N(patch.ply);}const impact=impactFor(model,roof,id);model.changeLog=model.changeLog||[];model.changeLog.push({time:new Date().toISOString(),id,type:o.type,before,patch,impact:impact.map(x=>x.id)});return{ok:true,object:o,impact};}
export function impactFor(model,roof,id){const g=model?.relationshipGraph;if(!g)return[];const ids=new Set([id]);let changed=true;while(changed){changed=false;for(const e of g.edges||[])if(ids.has(e.from)&&!ids.has(e.to)){ids.add(e.to);changed=true;}else if(ids.has(e.to)&&!ids.has(e.from)&&['bears-on','truss-to-truss'].includes(e.relation)){ids.add(e.from);changed=true;}}return (g.nodes||[]).filter(n=>ids.has(n.id));}
export function supportNodeRecords(model,roof){const rows=[];for(const p of model?.exactLoadPaths||[])rows.push({id:p.source,x:R(p.x),y:R(p.y),z:R((model.levels||1)*N(model.wallHeightFt)*.3048),loadKN:R(p.loadKN),support:p.support,offsetM:p.offsetM,status:p.status});model.supportNodes=rows;return rows;}
export function changeImpactCSV(model){return ['Time,Object,Type,Changed fields,Impacted objects',...(model.changeLog||[]).map(x=>[x.time,x.id,x.type,Object.keys(x.patch||{}).join(';'),(x.impact||[]).join(';')].map(csv).join(','))].join('\r\n');}
export function supportCSV(model){return ['Reaction,X_m,Y_m,Z_m,Load_kN,Support,Offset_m,Status',...(model.supportNodes||[]).map(x=>[x.id,x.x,x.y,x.z,x.loadKN,x.support,x.offsetM??'',x.status].map(csv).join(','))].join('\r\n');}
function csv(v){const s=String(v??'');return /[,"\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
