import {trussFrameGeometry} from './connection-geometry.js?v=16';
import {drawTrussElevation,trussSchedule,elevationHeight} from './truss-drawing.js?v=3';
import {woodTakeoff,STOCK_FT} from './takeoff.js?v=2';
// CadTech vector PDF writer - truss design-document format.
const clean=s=>String(s??'').replace(/×/g,'x').replace(/[^-]/g,'-').replace(/[\\()]/g,'\\$&');
const fmt=(v,n=2)=>Number.isFinite(v)?v.toFixed(n):'--';
export function makeReport(project,assembly,settings={},units='imperial'){
 const imperial=units!=='metric';
 const gcd=(a,b)=>b?gcd(b,a%b):a;
 const fracIn=(m)=>{if(!Number.isFinite(m))return '--';let total=m/0.0254,ft=Math.floor(total/12+1e-9),inch=total-ft*12,den=16,num=Math.round((inch-Math.floor(inch))*den),whole=Math.floor(inch);if(num===den){whole++;num=0}if(whole>=12){ft++;whole-=12}if(num){const g=gcd(num,den);num/=g;den/=g}return `${ft}'-${whole}${num?' '+num+'/'+den:''}\"`;};
 const dim=(m)=>imperial?fracIn(m):`${fmt(m*1000,0)} mm`;
 const dimShort=(m)=>imperial?fracIn(m):`${fmt(m,3)} m`;
 const pages=[];let c=[],y=750,pageNo=0;
 const text=(s,x,yy,size=9,color='0.10 0.14 0.18',font='F1')=>c.push(`BT /${font} ${size} Tf ${color} rg 1 0 0 1 ${x} ${yy} Tm (${clean(s)}) Tj ET`);
 const textRot=(s,x,yy,angle,size=7,color='0.10 0.14 0.18',font='F2')=>{let a=angle;while(a>90)a-=180;while(a<-90)a+=180;const r=a*Math.PI/180,cs=Math.cos(r).toFixed(5),sn=Math.sin(r).toFixed(5);c.push(`BT /${font} ${size} Tf ${color} rg ${cs} ${sn} ${(-Math.sin(r)).toFixed(5)} ${cs} ${x} ${yy} Tm (${clean(s)}) Tj ET`);};
 const line=(x1,y1,x2,y2,w=.5,color='0.55 0.62 0.67')=>c.push(`${color} RG ${w} w ${x1} ${y1} m ${x2} ${y2} l S`);
 const box=(x,yy,w,h,fill='0.94 0.96 0.97')=>c.push(`${fill} rg ${x} ${yy} ${w} ${h} re f`);
 const footer=()=>{line(28,34,567,34,.5,'0.10 0.35 0.55');text('CadTech - Wood Truss Design Documents',30,20,7,'0.25 0.30 0.34');text(`Page ${pageNo}`,520,20,7);};
 const finish=()=>{if(!c.length)return;footer();pages.push(c.join('\n'));c=[];};
 const page=(title,sub='')=>{finish();pageNo++;box(28,785,539,34,'0.06 0.28 0.46');text('CadTech',38,798,16,'1 1 1','F2');text('WOOD TRUSS DESIGN',115,799,8,'0.82 0.91 0.96','F2');text(project,360,799,9,'1 1 1');text(title,32,758,15,'0.06 0.28 0.46','F2');if(sub)text(sub,32,742,8,'0.35 0.40 0.44');y=sub?718:730;};
 const para=s=>{const words=String(s).split(/\s+/);let row='';for(const w of words){if((row+' '+w).length>105){if(y<60)page('Continued');text(row,32,y,8);y-=12;row=w}else row+=(row?' ':'')+w}if(row){if(y<60)page('Continued');text(row,32,y,8);y-=16}};
 const table=(heads,rows,widths)=>{const row=(cells,head=false)=>{if(y<58){page('Schedule continued');if(!head)row(heads,true)}let x=32;if(head)box(32,y-5,531,17,'0.88 0.92 0.95');cells.forEach((v,i)=>{text(String(v).slice(0,Math.max(4,Math.floor(widths[i]/4.5))),x+3,y,7.4,head?'0.06 0.28 0.46':'0.13 0.17 0.20',head?'F2':'F1');x+=widths[i]});line(32,y-6,563,y-6,.25);y-=18};row(heads,true);rows.forEach(r=>row(r));y-=8;};
 const loads=[['Dead',settings.dead],['Roof live',settings.roofLive],['Snow',settings.snow],['Wind / uplift',settings.wind],['Bottom chord live',settings.bottomLive],['Construction',settings.construction],['Special / solar',settings.special]];
 page('ROOF TRUSS DESIGN SUMMARY','CadTech project design record - no manufacturer or third-party branding');
 table(['General design information','Value'],[['Trusses',assembly.trusses.length],['Truss spacing / tributary width',`${settings.trib??'--'} ft`],['Heel / BC drop',dim((assembly.trusses[0]?.profile?.[0]?.[2]-assembly.base))],['Material','Dimensional wood lumber'],['Sections','2x4, 2x6, 2x8, 2x10, 2x12'],['Auto-design','Sizes 2x4-2x12, plies 1-5, web pattern, bearings, bearing length, jack loads on girders, hold-down / plate requirements, bracing'],['Deflection criterion',`L/${settings.limit??360}`]], [300,231]);
 table(['Applied load category','Input'],loads.map(([n,v])=>[n,`${v??'--'} psf`]),[300,231]);
 para('Design basis: 2D pin-jointed wood-truss FEM with gravity/uplift/service cases, member axial-force screening, displacement, reactions, timber size optimization, web-pattern optimization and optional bearing investigation.');
 para('ISSUE LIMITATION: This report is formatted as a construction-document design record, but connector/plate capacity, permanent and temporary bracing, full code-specific timber interaction, truss-to-truss connection design and project-specific certification are not automatically completed. Those items must be verified before construction issue.');
 {const done=assembly.trusses.filter(t=>t.analysis),pass=done.filter(t=>(t.design?.result||t.analysis.status)==='PASS').length;para(done.length?`ROOF DESIGN RESULT: ${pass===done.length?'PASS':'FAIL'} - ${pass} PASS${done.length-pass?`, ${done.length-pass} FAIL`:''} of ${done.length} analyzed trusses (${assembly.trusses.length-done.length} not analyzed). Sizes, plies, bearings, jack loads on girders, hold-down and plate requirements and bracing were designed automatically.`:'ROOF DESIGN RESULT: NOT ANALYZED - run Analyze to design and check every truss.');}
 table(['Truss','Family','Span','Heel','Ply','Web','Max ratio','Status'],assembly.trusses.map(t=>[t.id,t.type,dimShort(t.span),dim(t.profile[0][2]-t.base),t.analysis?.ply||t.ply,t.analysis?.style||t.webStyle||'--',fmt(t.analysis?.ratio,3),t.analysis?.status||'NOT ANALYZED']),[40,70,55,52,30,65,60,159]);
 // Roof truss layout page: plan view based on generated truss world geometry.
 page('ROOF TRUSS LAYOUT',`Plan view | dimensions: ${imperial?'feet-inches to nearest 1/16 inch':'metric'}`);
 {const pts=[];for(const t of assembly.trusses){for(const m of t.members){pts.push(m.a,m.b)}}if(pts.length){const minX=Math.min(...pts.map(p=>p[0])),maxX=Math.max(...pts.map(p=>p[0])),minY=Math.min(...pts.map(p=>p[1])),maxY=Math.max(...pts.map(p=>p[1])),W=Math.max(maxX-minX,.001),H=Math.max(maxY-minY,.001),sc=Math.min(485/W,520/H),ox=55+(485-W*sc)/2,oy=150+(520-H*sc)/2,P=p=>[ox+(p[0]-minX)*sc,oy+(p[1]-minY)*sc];box(38,120,519,590,'0.985 0.99 0.995');
 // Draw every generated wood member in true top-view position.  A minimum plotted width keeps 2x lumber visible at roof-plan scale.
 const sizeWidthM=size=>({"2x4":1.5,"2x6":1.5,"2x8":1.5,"2x10":1.5,"2x12":1.5}[size]||1.5)*0.0254;
 const memberPlan=(m,t,i)=>{const A=P(m.a),B=P(m.b),dx=B[0]-A[0],dy=B[1]-A[1],L=Math.hypot(dx,dy);if(L<.15)return;const r=t.analysis?.members?.find(x=>x.index===i),size=r?.size||m.sectionName||'2x4',ply=t.analysis?.ply||t.ply||1,actual=sizeWidthM(size)*Math.max(1,ply)*sc,w=Math.max(1.15,Math.min(5.0,actual)),nx=-dy/L*w/2,ny=dx/L*w/2,fill=t.type==='GIRDER'?'0.78 0.18 0.16':t.type==='STEPDOWN'?'0.88 0.48 0.08':(String(t.type).includes('JACK')?'0.10 0.55 0.28':String(t.type).includes('HIP')?'0.55 0.22 0.82':'0.76 0.63 0.30');c.push(`${fill} rg 0.16 0.20 0.23 RG .25 w ${A[0]+nx} ${A[1]+ny} m ${B[0]+nx} ${B[1]+ny} l ${B[0]-nx} ${B[1]-ny} l ${A[0]-nx} ${A[1]-ny} l h B`);};
 for(const t of assembly.trusses){for(let i=0;i<t.members.length;i++)memberPlan(t.members[i],t,i);let aa=null,bb=null,best=-1;for(const m of t.members){const d=Math.hypot(m.b[0]-m.a[0],m.b[1]-m.a[1]);if(d>best){best=d;aa=m.a;bb=m.b}}if(!aa)continue;const A=P(aa),B=P(bb),mx=(A[0]+B[0])/2,my=(A[1]+B[1])/2;box(mx-10,my-4,20,9,'1 1 1');text(t.id,mx-8,my-1,5.4,'0.05 0.08 0.10','F2');}
 // roof extents and overall dimensions
 c.push(`0.10 0.45 0.72 RG 1.0 w [4 3] 0 d ${ox} ${oy} ${W*sc} ${H*sc} re S [] 0 d`);const dy=oy+H*sc+18;line(ox,dy,ox+W*sc,dy,.5,'0.08 0.10 0.11');line(ox,dy-4,ox,dy+4,.5);line(ox+W*sc,dy-4,ox+W*sc,dy+4,.5);text(`OVERALL  ${dim(W)}`,ox+W*sc/2-35,dy+6,7,'0.05 0.08 0.10','F2');const dx=ox-18;line(dx,oy,dx,oy+H*sc,.5,'0.08 0.10 0.11');line(dx-4,oy,dx+4,oy,.5);line(dx-4,oy+H*sc,dx+4,oy+H*sc,.5);text(`WIDTH ${dim(H)}`,40,oy+H*sc/2,7,'0.05 0.08 0.10','F2');y=96;para('Roof plan shows every generated wood member in top view, including complete truss framing, truss marks and overall roof extents. Verify roof boundary, hips, valleys, bearings, openings, girder/jack relationships and connector requirements against the project drawings before construction issue.');}}
 const TO=woodTakeoff(assembly);
 const roofTakeoff=()=>{const to=TO,t=to.totals,n1=v=>Number(v).toFixed(1),sec=to.sections;
  page('WOOD TAKE-OFF','Cut list merged into continuous boards - long-point lengths - standard stock 8 to 24 ft - nominal board feet');
  table(['Roof total','Value'],[['Trusses',t.trusses],['Timbers (pieces cut)',t.pieces],['Cut length',`${n1(t.cutFt)} lin ft`],['Nominal board feet (cut)',`${n1(t.bf)} BF`],['Boards to order',`${t.boards}  (${n1(t.orderedFt)} lin ft, ${n1(t.orderedBf)} BF)`],['Yield before waste allowance',`${n1(t.orderedFt?t.cutFt/t.orderedFt*100:0)} %`],['Analysis status',t.analyzed<t.trusses?`${t.trusses-t.analyzed} of ${t.trusses} trusses not analyzed - template 2x4 sizes used`:'All trusses analyzed - final member sizes']],[300,231]);
  table(['Section','Pieces','Cut lin ft','Nominal BF','Boards','Order lin ft','Order BF','Yield'],sec.map(s=>[s.section,s.pieces,n1(s.cutFt),n1(s.bf),s.boards,n1(s.orderedFt),n1(s.orderedBf),n1(s.yield*100)+' %']),[70,60,75,75,60,75,60,56]);
  table(['Stock boards',...STOCK_FT.map(x=>`${x} ft`),'Spliced'],sec.map(s=>[s.section,...STOCK_FT.map(x=>s.stock[x]||'-'),s.splicePieces||'-']),[111,45,45,45,45,45,45,45,45,60]);
  table(['Role','Section','Pieces','Cut lin ft','Nominal BF'],to.byRole.sort((a,b)=>a.role.localeCompare(b.role)||a.section.localeCompare(b.section)).map(r=>[r.role,r.section,r.pieces,n1(r.cutFt),n1(r.bf)]),[110,110,100,110,101]);
  para('Take-off by truss (pieces counted per ply; chords merged into continuous boards, overhang included):');
  table(['Truss','Family','Plies','Pieces','Cut lin ft','Nominal BF'],to.byTruss.map(r=>[r.truss,r.type,r.plies,r.pieces,n1(r.cutFt),n1(r.bf)]),[80,130,60,80,90,91]);
  para('Stock boards are packed first-fit-decreasing with a 1/8 in saw kerf; chords longer than 24 ft are listed as spliced (24 ft board plus remainder). Webs and chord ends have angled cuts, so add a project waste allowance. The full piece-by-piece cut list is in wood-cutlist.csv.');
 };
 roofTakeoff();
 for(const t of assembly.trusses){const a=t.analysis;page(`${t.id} - ${t.type.toUpperCase()}`,`Truss mark ${t.id} | ${a?.status||'NOT ANALYZED'} | CadTech`);
  const gradeShort=(g=>g&&g!=='CUSTOM'?String(g).replace(/-?No2/i,' NO.2').replace(/-/g,' ').toUpperCase():'')(settings.woodGrade);
  table(['DESIGN INFORMATION','VALUE','DESIGN INFORMATION','VALUE'],[['Span',fmt(t.span,3)+' m','Height',fmt(t.height,3)+' m'],['Heel / BC drop',dim(t.profile[0][2]-t.base),'Ply',a?.ply||t.ply],['Web pattern',a?.style||t.webStyle||'--','Shape',t.shape||'Source profile'],['Max utilization',fmt(a?.ratio,3),'Service displacement',fmt(a?.displacement,2)+' mm'],['Governing case',a?.governingCase||'--','Lumber',gradeShort||'Dimensional wood']],[100,165,115,151]);
  // Shop-drawing style elevation (truss-drawing.js): exact cut lumber, plates, dimension strings, call-outs, marks.
  const G=trussFrameGeometry(t,assembly),sched=trussSchedule(t,assembly,G),rh=elevationHeight(t,assembly,531,340,G),rect={x:32,y:y-rh-6,w:531,h:rh};
  drawTrussElevation({c,text,line,dim,dimShort},t,assembly,rect,{geometry:G,schedule:sched,grade:gradeShort});y=rect.y-14;
  if(a?.loadCases?.length)table(['Load case','Line load kN/m','Total vertical kN'],a.loadCases.map(x=>[x.name,fmt(x.lineLoad_kNm,3),fmt(x.totalVertical_kN,2)]),[300,105,126]);
  const toRows=new Map(TO.rows.filter(r=>r.truss===t.id).map(r=>[r.idx.join(','),r]));
  table(['Mark','Role','Section','Ply','Cut length','Cut angles A / B','Stock','Nom. BF','Force kN','Ratio','Governing'],sched.map(r=>{const k=toRows.get(r.idx.join(','));return [r.mark,r.role+(r.overhang?' + tail':''),r.section,r.ply,dimShort(r.cutM),`${fmt(r.angA,1)} / ${fmt(r.angB,1)} deg`,k?`${k.stockFt??'>24'} ft`:'--',k?fmt(k.bf,1):'--',fmt(r.force,2),fmt(r.ratio,3),r.governing||'--'];}),[38,58,44,24,62,78,34,36,44,38,75]);
  {const mine=TO.rows.filter(r=>r.truss===t.id),by=new Map();
   for(const r of mine){if(!by.has(r.section))by.set(r.section,{section:r.section,boards:0,pieces:0,ft:0,bf:0,stock:{}});const g=by.get(r.section);g.boards++;g.pieces+=r.qty;g.ft+=r.cutFt*r.qty;g.bf+=r.bf;const k=r.stockFt??'>24';g.stock[k]=(g.stock[k]||0)+r.qty;}
   const stockTxt=g=>Object.entries(g.stock).sort((p,q)=>(parseFloat(p[0])||99)-(parseFloat(q[0])||99)).map(([k,n])=>`${n} x ${k} ft`).join(', '),tot=[...by.values()].reduce((m,g)=>({b:m.b+g.boards,p:m.p+g.pieces,f:m.f+g.ft,bf:m.bf+g.bf}),{b:0,p:0,f:0,bf:0});
   if(by.size)table(['WOOD TAKE-OFF - '+t.id,'Boards','Pieces','Cut lin ft','Nominal BF','Stock needed (one board per piece)'],[...by.values()].map(g=>[g.section,g.boards,g.pieces,fmt(g.ft,1),fmt(g.bf,1),stockTxt(g)]).concat([['TRUSS TOTAL',tot.b,tot.p,fmt(tot.f,1),fmt(tot.bf,1),'Roof-level order: see WOOD TAKE-OFF page']]),[110,50,50,66,70,185]);}
  para('Marks refer to the elevation above. Cut length is the long-point length of the continuous board (chord segments merged, overhang included). Cut angles are measured from a square cut at each end of the board (A = left or lower end, B = right or upper end).');
  if(a?.reactions?.length){const rr=a.reactions.flatMap((lc)=>lc.reactions.map((r,i)=>[lc.case,`B${i+1}`,dimShort(r.x),fmt(r.force,2)]));table(['Reaction load case','Bearing',imperial?'x ft-in':'x m','Vertical kN'],rr,[260,60,70,141]);}
  if(t.engineering?.checks){const e=t.engineering,c=e.checks;table(['DESIGN CHECK (auto-designed)','DEMAND','PROVIDED / REQUIRED','RESULT'],[['Strength + deflection',`ratio ${fmt(c.strength.ratio,3)}`,`${fmt(c.strength.displacement_mm,2)} mm deflection`,c.strength.status],['Bearing',fmt(c.bearing.demand_kN,2)+' kN',`${c.bearing.providedLength_mm} mm @ ${fmt(c.bearing.capacity_kN,2)} kN`,c.bearing.status],['Uplift / hold-down',fmt(c.uplift.demand_kN,2)+' kN',c.uplift.demand_kN>0?(c.uplift.capacity_kN?`${c.uplift.perBearing} x ${fmt(c.uplift.capacity_kN,1)} kN`:`>= ${fmt(c.uplift.requirement_kN,1)} kN tie`):'none',c.uplift.status],['Joint / plate',fmt(c.connections.demand_kN,2)+' kN',c.connections.userCapacity_kN?`${fmt(c.connections.userCapacity_kN,1)} kN entered`:`>= ${fmt(c.connections.requirement_kN,1)} kN each joint`,c.connections.status],['Compression restraint',`${c.bracing.flagged.length} member(s)`,c.bracing.flagged.length?'lateral restraint specified':'none needed',c.bracing.status],['Transferred loads',`${c.transfers.count} truss(es)`,c.transfers.count?'applied as nodal loads':'none',c.transfers.status]],[150,100,171,110]);
  if(t.design){para(`DESIGN RESULT: ${t.design.result}${t.design.failures.length?' - '+t.design.failures.join('; '):''}`);if(t.design.actions.length)para('Automatic design changes: '+t.design.actions.join('; ')+'.');if(c.bracing.flagged.length)table(['Braced member','Role','Length','Brace points','Max unbraced'],c.bracing.flagged.map(x=>[x.member,x.role,dimShort(x.length_m),x.braces,dimShort(x.spacing_m)]),[100,90,100,110,131]);};if(e.transfersIn?.length)table(['TRANSFER FROM','CASE','REACTION kN','STATUS'],e.transfersIn.map(x=>[x.from,x.case,fmt(x.designReaction_kN,2),x.status]),[80,130,90,231]);table(['Cost model','Timber','Plates','Labor','Total'],[['User relative cost',fmt(e.cost.timber,2),fmt(e.cost.plates,2),fmt(e.cost.labor,2),fmt(e.cost.total,2)]],[120,100,100,100,111]);para(`Workflow: ${e.codeProfile||'CUSTOM'} | Wood grade: ${e.woodGrade||'CUSTOM'} | Revision: ${e.revision||'A'}. Generic connection and cost values are project inputs, not proprietary manufacturer design data.`);}
  para('JOINT / CONNECTION NOTE: Member axes are geometrically continuous and 3D solids overlap at panel points to eliminate display gaps. Final saw cuts, metal connector plates/fasteners, plate orientation, teeth/fastener capacity and fabrication tolerances require connection design and shop detailing.');
  para(t.review||'');
 }
 page('ISSUE NOTES');

 para('CadTech report intentionally contains no CadTech, fabricator, client-company or third-party certification branding. Project-specific title-block fields may be added by the user.');para('Before issue for construction: verify selected design standard and all load inputs; engineer connector plates/fasteners and splices; verify lateral restraint and permanent/temporary bracing; verify girder/jack transfers, bearings, uplift/tie-downs and foundations; and obtain required professional certification/approval.');
 finish();const objs=[null,'<< /Type /Catalog /Pages 2 0 R >>',null,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'],kids=[];for(const stream of pages){const pn=objs.length,cn=pn+1;kids.push(`${pn} 0 R`);objs.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${cn} 0 R >>`);objs.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`)}objs[2]=`<< /Type /Pages /Count ${pages.length} /Kids [${kids.join(' ')}] >>`;let out='%PDF-1.4\n',offs=[0];for(let i=1;i<objs.length;i++){offs.push(out.length);out+=`${i} 0 obj\n${objs[i]}\nendobj\n`}const start=out.length;out+=`xref\n0 ${objs.length}\n0000000000 65535 f \n`+offs.slice(1).map(n=>`${String(n).padStart(10,'0')} 00000 n \n`).join('')+`trailer\n<< /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return new TextEncoder().encode(out);
}
