// CadTech vector PDF writer - truss design-document format.
const clean=s=>String(s??'').replace(/×/g,'x').replace(/[^-]/g,'-').replace(/[\\()]/g,'\\$&');
const fmt=(v,n=2)=>Number.isFinite(v)?v.toFixed(n):'--';
export function makeReport(project,assembly,settings={},units='imperial'){
 const imperial=units!=='metric';
 const gcd=(a,b)=>b?gcd(b,a%b):a;
 const fracIn=(m)=>{if(!Number.isFinite(m))return '--';let total=m/0.0254,ft=Math.floor(total/12+1e-9),inch=total-ft*12,den=16,num=Math.round((inch-Math.floor(inch))*den),whole=Math.floor(inch);if(num===den){whole++;num=0}if(whole>=12){ft++;whole-=12}if(num){const g=gcd(num,den);num/=g;den/=g}return `${ft}'-${whole}${num?' '+num+'/'+den:''}\"`;};
 const dim=(m)=>imperial?fracIn(m):`${fmt(m*1000,0)} mm`;
 const dimShort=(m)=>imperial?fracIn(m):`${fmt(m,3)} m`;
 const pages=[];let c=[],y=750,pageNo=0;
 const text=(s,x,yy,size=9,color='0.10 0.14 0.18',font='F1')=>c.push(`BT /${font} ${size} Tf ${color} rg 1 0 0 1 ${x} ${yy} Tm (${clean(s)}) Tj ET`);
 const textRot=(s,x,yy,angle,size=7,color='0.10 0.14 0.18',font='F2')=>{let a=angle;while(a>90)a-=180;while(a<-90)a+=180;const r=a*Math.PI/180,cs=Math.cos(r).toFixed(5),sn=Math.sin(r).toFixed(5);c.push(`BT /${font} ${size} Tf ${color} rg ${cs} ${sn} ${(-Math.sin(r)).toFixed(5)} ${cs} ${x} ${yy} Tm (${clean(s)}) Tj ET`);};
 const line=(x1,y1,x2,y2,w=.5,color='0.55 0.62 0.67')=>c.push(`${color} RG ${w} w ${x1} ${y1} m ${x2} ${y2} l S`);
 const box=(x,yy,w,h,fill='0.94 0.96 0.97')=>c.push(`${fill} rg ${x} ${yy} ${w} ${h} re f`);
 const footer=()=>{line(28,34,567,34,.5,'0.10 0.35 0.55');text('CadTech - Wood Truss Design Documents',30,20,7,'0.25 0.30 0.34');text(`Page ${pageNo}`,520,20,7);};
 const finish=()=>{if(!c.length)return;footer();pages.push(c.join('\n'));c=[];};
 const page=(title,sub='')=>{finish();pageNo++;box(28,785,539,34,'0.06 0.28 0.46');text('CadTech',38,798,16,'1 1 1','F2');text('WOOD TRUSS DESIGN',115,799,8,'0.82 0.91 0.96','F2');text(project,360,799,9,'1 1 1');text(title,32,758,15,'0.06 0.28 0.46','F2');if(sub)text(sub,32,742,8,'0.35 0.40 0.44');y=sub?718:730;};
 const para=s=>{const words=String(s).split(/\s+/);let row='';for(const w of words){if((row+' '+w).length>105){if(y<60)page('Continued');text(row,32,y,8);y-=12;row=w}else row+=(row?' ':'')+w}if(row){if(y<60)page('Continued');text(row,32,y,8);y-=16}};
 const table=(heads,rows,widths)=>{const row=(cells,head=false)=>{if(y<58){page('Schedule continued');row(heads,true)}let x=32;if(head)box(32,y-5,531,17,'0.88 0.92 0.95');cells.forEach((v,i)=>{text(String(v).slice(0,Math.max(4,Math.floor(widths[i]/4.5))),x+3,y,7.4,head?'0.06 0.28 0.46':'0.13 0.17 0.20',head?'F2':'F1');x+=widths[i]});line(32,y-6,563,y-6,.25);y-=18};row(heads,true);rows.forEach(r=>row(r));y-=8;};
 const loads=[['Dead',settings.dead],['Roof live',settings.roofLive],['Snow',settings.snow],['Wind / uplift',settings.wind],['Bottom chord live',settings.bottomLive],['Construction',settings.construction],['Special / solar',settings.special]];
 page('ROOF TRUSS DESIGN SUMMARY','CadTech project design record - no manufacturer or third-party branding');
 table(['General design information','Value'],[['Trusses',assembly.trusses.length],['Truss spacing / tributary width',`${settings.trib??'--'} ft`],['Heel / BC drop',dim((assembly.trusses[0]?.profile?.[0]?.[2]-assembly.base))],['Material','Dimensional wood lumber'],['Sections','2x4, 2x6, 2x8, 2x10, 2x12'],['Ply optimization','1-ply -> 2-ply -> 3-ply'],['Deflection criterion',`L/${settings.limit??360}`]], [300,231]);
 table(['Applied load category','Input'],loads.map(([n,v])=>[n,`${v??'--'} psf`]),[300,231]);
 para('Design basis: 2D pin-jointed wood-truss FEM with gravity/uplift/service cases, member axial-force screening, displacement, reactions, timber size optimization, web-pattern optimization and optional bearing investigation.');
 para('ISSUE LIMITATION: This report is formatted as a construction-document design record, but connector/plate capacity, permanent and temporary bracing, full code-specific timber interaction, truss-to-truss connection design and project-specific certification are not automatically completed. Those items must be verified before construction issue.');
 table(['Truss','Family','Span','Heel','Ply','Web','Max ratio','Status'],assembly.trusses.map(t=>[t.id,t.type,dimShort(t.span),dim(t.profile[0][2]-t.base),t.analysis?.ply||t.ply,t.analysis?.style||t.webStyle||'--',fmt(t.analysis?.ratio,3),t.analysis?.status||'NOT ANALYZED']),[40,70,55,52,30,65,60,159]);
 // Roof truss layout page: plan view based on generated truss world geometry.
 page('ROOF TRUSS LAYOUT',`Plan view | dimensions: ${imperial?'feet-inches to nearest 1/16 inch':'metric'}`);
 {const pts=[];for(const t of assembly.trusses){for(const m of t.members){pts.push(m.a,m.b)}}if(pts.length){const minX=Math.min(...pts.map(p=>p[0])),maxX=Math.max(...pts.map(p=>p[0])),minY=Math.min(...pts.map(p=>p[1])),maxY=Math.max(...pts.map(p=>p[1])),W=Math.max(maxX-minX,.001),H=Math.max(maxY-minY,.001),sc=Math.min(485/W,520/H),ox=55+(485-W*sc)/2,oy=150+(520-H*sc)/2,P=p=>[ox+(p[0]-minX)*sc,oy+(p[1]-minY)*sc];box(38,120,519,590,'0.985 0.99 0.995');
 // Draw every generated wood member in true top-view position.  A minimum plotted width keeps 2x lumber visible at roof-plan scale.
 const sizeWidthM=size=>({"2x4":1.5,"2x6":1.5,"2x8":1.5,"2x10":1.5,"2x12":1.5}[size]||1.5)*0.0254;
 const memberPlan=(m,t,i)=>{const A=P(m.a),B=P(m.b),dx=B[0]-A[0],dy=B[1]-A[1],L=Math.hypot(dx,dy);if(L<.15)return;const r=t.analysis?.members?.find(x=>x.index===i),size=r?.size||m.sectionName||'2x4',ply=t.analysis?.ply||t.ply||1,actual=sizeWidthM(size)*Math.max(1,ply)*sc,w=Math.max(1.15,Math.min(5.0,actual)),nx=-dy/L*w/2,ny=dx/L*w/2,fill=t.type==='GIRDER'?'0.78 0.18 0.16':t.type==='STEPDOWN'?'0.88 0.48 0.08':(String(t.type).includes('JACK')?'0.10 0.55 0.28':String(t.type).includes('HIP')?'0.55 0.22 0.82':'0.76 0.63 0.30');c.push(`${fill} rg 0.16 0.20 0.23 RG .25 w ${A[0]+nx} ${A[1]+ny} m ${B[0]+nx} ${B[1]+ny} l ${B[0]-nx} ${B[1]-ny} l ${A[0]-nx} ${A[1]-ny} l h B`);};
 for(const t of assembly.trusses){for(let i=0;i<t.members.length;i++)memberPlan(t.members[i],t,i);let aa=null,bb=null,best=-1;for(const m of t.members){const d=Math.hypot(m.b[0]-m.a[0],m.b[1]-m.a[1]);if(d>best){best=d;aa=m.a;bb=m.b}}if(!aa)continue;const A=P(aa),B=P(bb),mx=(A[0]+B[0])/2,my=(A[1]+B[1])/2;box(mx-10,my-4,20,9,'1 1 1');text(t.id,mx-8,my-1,5.4,'0.05 0.08 0.10','F2');}
 // roof extents and overall dimensions
 c.push(`0.10 0.45 0.72 RG 1.0 w [4 3] 0 d ${ox} ${oy} ${W*sc} ${H*sc} re S [] 0 d`);const dy=oy+H*sc+18;line(ox,dy,ox+W*sc,dy,.5,'0.08 0.10 0.11');line(ox,dy-4,ox,dy+4,.5);line(ox+W*sc,dy-4,ox+W*sc,dy+4,.5);text(`OVERALL  ${dim(W)}`,ox+W*sc/2-35,dy+6,7,'0.05 0.08 0.10','F2');const dx=ox-18;line(dx,oy,dx,oy+H*sc,.5,'0.08 0.10 0.11');line(dx-4,oy,dx+4,oy,.5);line(dx-4,oy+H*sc,dx+4,oy+H*sc,.5);text(`WIDTH ${dim(H)}`,40,oy+H*sc/2,7,'0.05 0.08 0.10','F2');y=96;para('Roof plan shows every generated wood member in top view, including complete truss framing, truss marks and overall roof extents. Verify roof boundary, hips, valleys, bearings, openings, girder/jack relationships and connector requirements against the project drawings before construction issue.');}}
 for(const t of assembly.trusses){const a=t.analysis;page(`${t.id} - ${t.type.toUpperCase()}`,`Truss mark ${t.id} | ${a?.status||'NOT ANALYZED'} | CadTech`);
  table(['TRUSS DESIGN INFORMATION','VALUE'],[['Span',fmt(t.span,3)+' m'],['Height',fmt(t.height,3)+' m'],['Heel / bottom-chord drop',dim(t.profile[0][2]-t.base)],['Ply',a?.ply||t.ply],['Web pattern',a?.style||t.webStyle||'--'],['Shape',t.shape||'Source profile'],['Max utilization ratio',fmt(a?.ratio,3)],['Service displacement',fmt(a?.displacement,2)+' mm'],['Governing load case',a?.governingCase||'--']], [300,231]);
  // Fabrication-style truss elevation: members are drawn at timber depth, not as analytical single lines.
  const origin=t.profile[0],end=t.profile.at(-1),span=Math.max(t.span,.001),u=[(end[0]-origin[0])/span,(end[1]-origin[1])/span],h=Math.max(t.height,.2),sc=Math.min(475/span,138/h),by=y-152,local=p=>[((p[0]-origin[0])*u[0]+(p[1]-origin[1])*u[1]),p[2]-t.base],pt=p=>{const q=local(p);return[58+q[0]*sc,by+q[1]*sc]};
  const poly=(P,fill='0.93 0.90 0.79',stroke='0.08 0.10 0.11')=>{c.push(`${fill} rg ${stroke} RG 0.65 w ${P[0][0]} ${P[0][1]} m `+P.slice(1).map(q=>`${q[0]} ${q[1]} l`).join(' ')+` h B`)};
  const depthIn=size=>({"2x4":3.5,"2x6":5.5,"2x8":7.25,"2x10":9.25,"2x12":11.25}[size]||3.5),inch=.0254;
  box(36,by-26,523,198,'0.985 0.99 0.995');
  const nodes=[];for(const m of t.members){const A=pt(m.a),B=pt(m.b),dx=B[0]-A[0],dy=B[1]-A[1],L=Math.hypot(dx,dy)||1,r=t.analysis?.members?.find(x=>x.index===t.members.indexOf(m)),size=r?.size||m.sectionName||'2x4',th=Math.max(3.2,depthIn(size)*inch*sc),nx=-dy/L*th/2,ny=dx/L*th/2,ext=Math.min(th*.38,5),ex=dx/L*ext,ey=dy/L*ext;poly([[A[0]-ex+nx,A[1]-ey+ny],[B[0]+ex+nx,B[1]+ey+ny],[B[0]+ex-nx,B[1]+ey-ny],[A[0]-ex-nx,A[1]-ey-ny]]);const mx=(A[0]+B[0])/2,my=(A[1]+B[1])/2,role=m.role==='top'?'T':m.role==='bottom'?'B':'W',idx=t.members.filter((q,j)=>j<=t.members.indexOf(m)&&q.role===m.role).length,ang=Math.atan2(dy,dx)*180/Math.PI,labelOff=th/2+5+(role==='W'?(idx%2)*5:0),lx=mx+(-dy/L)*labelOff,ly=my+(dx/L)*labelOff; textRot(`${role}${idx}  ${size}${(t.analysis?.ply||t.ply||1)>1?'  '+(t.analysis?.ply||t.ply)+'-PLY':''}`,lx,ly,ang,6.3,'0.05 0.08 0.10','F2');nodes.push(local(m.a),local(m.b));}
  // Joint marks and joint numbers.
  const uniq=[];for(const q of nodes){if(!uniq.some(n=>Math.hypot(n[0]-q[0],n[1]-q[1])<.006))uniq.push(q)}uniq.sort((a,b)=>a[0]-b[0]||a[1]-b[1]);uniq.forEach((q,i)=>{const P=[58+q[0]*sc,by+q[1]*sc];c.push(`1 1 1 rg 0.05 0.08 0.10 RG .55 w ${P[0]-2.5} ${P[1]-2.5} 5 5 re B`);text(String(i+1),P[0]-2,P[1]+7,6.5,'0.05 0.08 0.10','F2')});
  // Overall and panel dimensions below the bottom chord.
  const xs=[...new Set(uniq.filter(q=>Math.abs(q[1])<Math.max(.025,h*.03)).map(q=>Math.round(q[0]*1000)/1000))].sort((a,b)=>a-b);const allLocal=t.members.flatMap(m=>[local(m.a),local(m.b)]),outMin=Math.min(...allLocal.map(q=>q[0])),outMax=Math.max(...allLocal.map(q=>q[0])),outLen=outMax-outMin,dimY=by-14;line(58,dimY,58+span*sc,dimY,.45,'0.08 0.10 0.11');line(58,dimY-4,58,dimY+4,.45,'0.08 0.10 0.11');line(58+span*sc,dimY-4,58+span*sc,dimY+4,.45,'0.08 0.10 0.11');text(`BEARING / PROFILE SPAN  ${dimShort(t.span)}`,190,dimY-11,7.1,'0.05 0.08 0.10','F2');const outY=dimY-25,outX1=58+outMin*sc,outX2=58+outMax*sc;line(outX1,outY,outX2,outY,.55,'0.06 0.28 0.46');line(outX1,outY-4,outX1,outY+4,.55,'0.06 0.28 0.46');line(outX2,outY-4,outX2,outY+4,.55,'0.06 0.28 0.46');text(`OUT-TO-OUT  ${dimShort(outLen)}`,(outX1+outX2)/2-45,outY-11,7.5,'0.06 0.28 0.46','F2');for(let i=0;i<xs.length-1;i++){const x1=58+xs[i]*sc,x2=58+xs[i+1]*sc;line(x1,dimY+8,x2,dimY+8,.3);line(x1,dimY+5,x1,dimY+11,.3);line(x2,dimY+5,x2,dimY+11,.3);if(x2-x1>28)text(`${dim(xs[i+1]-xs[i])}`,(x1+x2)/2-14,dimY+12,6.2)}
  // Vertical overall height dimension and pitch note.
  const xDim=45;line(xDim,by,xDim,by+h*sc,.4,'0.08 0.10 0.11');line(xDim-3,by,xDim+3,by,.4);line(xDim-3,by+h*sc,xDim+3,by+h*sc,.4);text(`H ${dimShort(h)}`,38,by+h*sc/2,6.5);const pitchDeg=t.profile.length>1?Math.atan2(t.profile[1][2]-t.profile[0][2],Math.max(.0001,Math.hypot(t.profile[1][0]-t.profile[0][0],t.profile[1][1]-t.profile[0][1])))*180/Math.PI:0;text(`PITCH ${fmt(Math.abs(pitchDeg),2)} deg`,65,by+158,7,'0.05 0.08 0.10','F2');y=by-66;
  if(a?.loadCases?.length)table(['Load case','Line load kN/m','Total vertical kN'],a.loadCases.map(x=>[x.name,fmt(x.lineLoad_kNm,3),fmt(x.totalVertical_kN,2)]),[300,105,126]);
  table(['Mem','Role','Length','Section','Ply','Force kN','Ratio','Governing'],t.members.map((m,i)=>{const r=a?.members?.find(x=>x.index===i);return [`M${i+1}`,m.role,dimShort(m.length),r?.size||m.sectionName||'2x4',a?.ply||t.ply,fmt(r?.force,2),fmt(r?.ratio,3),r?.governing||'--']}),[35,50,55,62,30,60,50,189]);
  if(a?.reactions?.length){const rr=a.reactions.flatMap((lc)=>lc.reactions.map((r,i)=>[lc.case,`B${i+1}`,dimShort(r.x),fmt(r.force,2)]));table(['Reaction load case','Bearing',imperial?'x ft-in':'x m','Vertical kN'],rr,[260,60,70,141]);}
  if(t.engineering?.checks){const e=t.engineering,c=e.checks;table(['ENGINEERING / QA CHECK','DEMAND','CAPACITY / FLAG','STATUS'],[['Bearing',fmt(c.bearing.demand_kN,2)+' kN',fmt(c.bearing.capacity_kN,2)+' kN',c.bearing.status],['Uplift / hold-down',fmt(c.uplift.demand_kN,2)+' kN',fmt(c.uplift.capacity_kN,2)+' kN',c.uplift.status],['Generic joint / plate',fmt(c.connections.demand_kN,2)+' kN',fmt(c.connections.userCapacity_kN,2)+' kN',c.connections.status],['Compression restraint',String(c.bracing.flagged.length)+' member(s)','Review flagged members',c.bracing.status]],[145,115,150,121]);if(e.transfersIn?.length)table(['TRANSFER FROM','CASE','REACTION kN','STATUS'],e.transfersIn.map(x=>[x.from,x.case,fmt(x.designReaction_kN,2),x.status]),[80,130,90,231]);table(['Cost model','Timber','Plates','Labor','Total'],[['User relative cost',fmt(e.cost.timber,2),fmt(e.cost.plates,2),fmt(e.cost.labor,2),fmt(e.cost.total,2)]],[120,100,100,100,111]);para(`Workflow: ${e.codeProfile||'CUSTOM'} | Wood grade: ${e.woodGrade||'CUSTOM'} | Revision: ${e.revision||'A'}. Generic connection and cost values are project inputs, not proprietary manufacturer design data.`);}
  para('JOINT / CONNECTION NOTE: Member axes are geometrically continuous and 3D solids overlap at panel points to eliminate display gaps. Final saw cuts, metal connector plates/fasteners, plate orientation, teeth/fastener capacity and fabrication tolerances require connection design and shop detailing.');
  para(t.review||'');
 }
 page('MATERIAL TAKEOFF / ISSUE NOTES');const take={};for(const t of assembly.trusses)for(let i=0;i<t.members.length;i++){const m=t.members[i],r=t.analysis?.members?.find(x=>x.index===i),size=r?.size||m.sectionName||'2x4',ply=t.analysis?.ply||t.ply||1,k=`${m.role}|${size}`;take[k]??={role:m.role,size,count:0,L:0};take[k].count+=ply;take[k].L+=m.length*ply}table(['Role','Timber section','Pieces',imperial?'Total length ft-in':'Total length m'],Object.values(take).map(r=>[r.role,r.size,r.count,dimShort(r.L)]),[90,190,80,171]);para('CadTech report intentionally contains no CadTech, fabricator, client-company or third-party certification branding. Project-specific title-block fields may be added by the user.');para('Before issue for construction: verify selected design standard and all load inputs; engineer connector plates/fasteners and splices; verify lateral restraint and permanent/temporary bracing; verify girder/jack transfers, bearings, uplift/tie-downs and foundations; and obtain required professional certification/approval.');
 finish();const objs=[null,'<< /Type /Catalog /Pages 2 0 R >>',null,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'],kids=[];for(const stream of pages){const pn=objs.length,cn=pn+1;kids.push(`${pn} 0 R`);objs.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${cn} 0 R >>`);objs.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`)}objs[2]=`<< /Type /Pages /Count ${pages.length} /Kids [${kids.join(' ')}] >>`;let out='%PDF-1.4\n',offs=[0];for(let i=1;i<objs.length;i++){offs.push(out.length);out+=`${i} 0 obj\n${objs[i]}\nendobj\n`}const start=out.length;out+=`xref\n0 ${objs.length}\n0000000000 65535 f \n`+offs.slice(1).map(n=>`${String(n).padStart(10,'0')} 00000 n \n`).join('')+`trailer\n<< /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return new TextEncoder().encode(out);
}
