import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {typeColors} from './roof.js?v=3';
import {solidMemberEnds} from './connection-geometry.js?v=3';
export class RoofViewer{
 constructor(host,onSelect){this.host=host;this.onSelect=onSelect;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#111d28');this.renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.localClippingEnabled=true;this.renderer.outputColorSpace=THREE.SRGBColorSpace;host.append(this.renderer.domElement);this.camera=new THREE.PerspectiveCamera(38,1,.01,1000);this.camera.up.set(0,0,1);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.screenSpacePanning=true;this.scene.add(new THREE.HemisphereLight(0xe6f3ff,0x718198,2.2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(4,-5,12);this.scene.add(sun);const fill=new THREE.DirectionalLight(0x9bbfff,2);fill.position.set(-8,3,4);this.scene.add(fill);this.root=new THREE.Group();this.scene.add(this.root);this.rafters=new THREE.Group();this.roof=new THREE.Group();this.scene.add(this.rafters,this.roof);this.grid=new THREE.GridHelper(20,40,0x435765,0x253645);this.grid.rotation.x=Math.PI/2;this.scene.add(this.grid);this.hit=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.layers={top:true,bottom:true,web:true,rafters:false,roof:false,labels:false,overhang:true};this.cut=new THREE.Plane(new THREE.Vector3(-1,0,0),1000);this.objects=[];this.labels=[];this.selected=null;this.mode='iso';this.filter='All';this.isolate=false;this.geometryCache=new Map();this.colorMode='type';this.controls.addEventListener('change',()=>this.render());this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);let down=null;this.renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);this.renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const rect=this.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);this.hit.setFromCamera(this.pointer,this.camera);const hits=this.hit.intersectObjects(this.objects.filter(o=>o.visible));const hit=hits.find(h=>this.cut.distanceToPoint(h.point)>=0);if(hit)this.onSelect(hit.object.userData.id,hit.object.userData.index);});this.renderer.setAnimationLoop(()=>{this.controls.update();this.render()});}
 clear(group){for(const o of [...group.children]){group.remove(o);o.traverse(x=>{if(x.geometry&&!x.userData.cached)x.geometry.dispose();if(x.material){x.material.map?.dispose();x.material.dispose();}});}}
 setModel(source,assembly){this.source=source;this.assembly=assembly;this.clear(this.root);this.clear(this.rafters);this.clear(this.roof);this.objects=[];this.labels=[];
 for(const m of source.meshes){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(m.positions,3));g.computeVertexNormals();const mat=new THREE.MeshStandardMaterial({color:m.kind==='surface'?0x84bfd0:0x7b8b99,transparent:true,opacity:m.kind==='surface'?.12:.32,side:THREE.DoubleSide,depthWrite:false});const mesh=new THREE.Mesh(g,mat);(m.kind==='surface'?this.roof:this.rafters).add(mesh);}
 if(!source.meshes.length)for(const a of source.axes){const g=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...a.a),new THREE.Vector3(...a.b)]);this.rafters.add(new THREE.Line(g,new THREE.LineBasicMaterial({color:0x8da3ad})));}
 for(const t of assembly.trusses){for(let ply=0;ply<t.ply;ply++)for(const [mi,m] of t.members.entries()){const [b,d]=m.section,offset=(ply-(t.ply-1)/2)*.055,trim=solidMemberEnds(t,m,assembly,offset);if(trim.hidden)continue;const aa=trim.a.map((x,i)=>x+(i<2?t.normal[i]*offset:0)),bb=trim.b.map((x,i)=>x+(i<2?t.normal[i]*offset:0)),axis=new THREE.Vector3(...bb).sub(new THREE.Vector3(...aa)),rawL=axis.length(),/* Connected solids are already face-trimmed. Never extend rectangular timber beyond analytical endpoints: this caused ridge spikes and hanging heels. */a=new THREE.Vector3(...aa),v=new THREE.Vector3(...bb).sub(a),L=v.length(),key=`${m.material||'timber'}/${b}/${d}/${m.thickness||.0381}/${L.toFixed(5)}`;let geometry=this.geometryCache.get(key);if(!geometry){const thick=m.thickness||.0381,lip=.015,pts=[[0,-d/2],[b,-d/2],[b,-d/2+lip],[b-thick,-d/2+lip],[b-thick,-d/2+thick],[thick,-d/2+thick],[thick,d/2-thick],[b-thick,d/2-thick],[b-thick,d/2-lip],[b,d/2-lip],[b,d/2],[0,d/2]],shape=new THREE.Shape();pts.forEach(([x,y],i)=>i?shape.lineTo(x-b/2,y):shape.moveTo(x-b/2,y));shape.closePath();geometry=new THREE.BoxGeometry(b,d,L).translate(0,0,L/2);this.geometryCache.set(key,geometry);}
 const mat=new THREE.MeshStandardMaterial({color:typeColors[t.type]||'#b9cad7',metalness:0,roughness:.82,side:THREE.DoubleSide,clippingPlanes:[this.cut]}),mesh=new THREE.Mesh(geometry,mat),z=v.normalize(),x=new THREE.Vector3(t.normal[0],t.normal[1],0).normalize(),y=new THREE.Vector3().crossVectors(z,x).normalize(),matrix=new THREE.Matrix4().makeBasis(x,y,z);mesh.quaternion.setFromRotationMatrix(matrix);mesh.position.copy(a);mesh.userData={id:t.id,role:m.role,index:mi,cached:true,type:t.type};this.root.add(mesh);this.objects.push(mesh);}
 const can=document.createElement('canvas');can.width=256;can.height=96;const ctx=can.getContext('2d');ctx.fillStyle='#142431dd';ctx.fillRect(0,0,256,96);ctx.fillStyle=typeColors[t.type];ctx.font='600 42px sans-serif';ctx.textAlign='center';ctx.fillText(t.id,128,63);const tex=new THREE.CanvasTexture(can),label=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,depthTest:false,transparent:true})),mid=t.profile[Math.floor(t.profile.length/2)];label.position.set(mid[0],mid[1],mid[2]+.25);label.scale.set(.65,.24,1);label.userData={id:t.id,type:t.type};this.root.add(label);this.labels.push(label);}
 this.grid.position.z=assembly.base-.1;this.extent=Math.max(...source.bounds.slice(0,2),3);this.grid.scale.setScalar(this.extent/12);this.updateVisibility();this.fit();}
 updateVisibility(){for(const o of this.objects){const selected=o.userData.id===this.selected; o.visible=this.layers[o.userData.role]&&(this.filter==='All'||o.userData.type===this.filter)&&(!this.isolate||selected);o.material.color.set(this.colorMode==='role'?({top:'#c9ed80',bottom:'#68baff',web:'#d4dde5',overhang:'#edac82'}[o.userData.role]):typeColors[o.userData.type]);o.material.emissive.set(selected?'#25492d':'#000000');o.material.emissiveIntensity=selected?.6:0;o.material.wireframe=this.colorMode==='wire';}this.rafters.visible=this.layers.rafters&&!this.isolate;this.roof.visible=this.layers.roof&&!this.isolate;for(const label of this.labels)label.visible=this.layers.labels&&(this.filter==='All'||label.userData.type===this.filter)&&(!this.isolate||label.userData.id===this.selected);this.render();}
 select(id){this.selected=id;this.updateVisibility();}
 resize(){const w=Math.max(1,this.host.clientWidth),h=Math.max(1,this.host.clientHeight);this.renderer.setSize(w,h,false);if(this.camera.isPerspectiveCamera)this.camera.aspect=w/h;else{const size=this.orthoSize||this.extent||10;this.camera.left=-size*w/h/2;this.camera.right=size*w/h/2;this.camera.top=size/2;this.camera.bottom=-size/2;}this.camera.updateProjectionMatrix();this.render();}
 setView(mode){this.mode=mode;const target=this.controls.target.clone(),old=this.camera;this.controls.dispose();this.camera=mode==='iso'?new THREE.PerspectiveCamera(38,1,.01,1000):new THREE.OrthographicCamera(-10,10,10,-10,.01,1000);this.camera.up.set(0,0,1);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.screenSpacePanning=true;this.controls.enableRotate=mode==='iso';if(mode!=='iso')this.controls.mouseButtons.LEFT=THREE.MOUSE.PAN;this.controls.addEventListener('change',()=>this.render());this.fit();}
 fit(){if(!this.assembly)return;let box=new THREE.Box3();for(const t of this.assembly.trusses){if(this.isolate&&t.id!==this.selected)continue;for(const m of t.members){box.expandByPoint(new THREE.Vector3(...m.a));box.expandByPoint(new THREE.Vector3(...m.b));}}const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),radius=Math.max(...size.toArray(),1),aspect=Math.max(.2,this.host.clientWidth/this.host.clientHeight);this.controls.target.copy(center);this.orthoSize=Math.max(size.z,size.y,size.x/aspect,2)*1.35;const distance=Math.max(size.length()/2,1)*1.18/Math.sin(Math.atan(Math.tan(19*Math.PI/180)*Math.min(1,aspect)));const dirs={iso:[1.15,-1.4,1],plan:[0,0,1],front:[0,-1,0],side:[1,0,0]};this.camera.up.set(...(this.mode==='plan'?[0,1,0]:[0,0,1]));this.camera.position.copy(center).add(new THREE.Vector3(...dirs[this.mode]).normalize().multiplyScalar(distance));this.camera.lookAt(center);this.resize();this.controls.update();}
 section(value){this.cut.constant=value>=100?1000:((value/100)-.5)*(this.source?.bounds[0]||10);this.render();}
 render(){if(this.renderer&&this.camera)this.renderer.render(this.scene,this.camera);}
 exportPNG(){this.render();return this.renderer.domElement.toDataURL('image/png');}
 dispose(){this.renderer.setAnimationLoop(null);this.resizeObserver.disconnect();this.controls.dispose();for(const g of [this.root,this.rafters,this.roof])this.clear(g);this.geometryCache.forEach(g=>g.dispose());this.renderer.dispose();}
}
